// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: binarypayload.proto

package cotproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`            // type identifier for the BinaryPayload. Use this type to determine decoding strategy
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`      // version identifier for the binary message
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`            // binary message payload data
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // timestamp when ingested
	Uuid          string                 `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`            // unique id for this BinaryPayload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryPayload) Reset() {
	*x = BinaryPayload{}
	mi := &file_binarypayload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryPayload) ProtoMessage() {}

func (x *BinaryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_binarypayload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryPayload.ProtoReflect.Descriptor instead.
func (*BinaryPayload) Descriptor() ([]byte, []int) {
	return file_binarypayload_proto_rawDescGZIP(), []int{0}
}

func (x *BinaryPayload) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BinaryPayload) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BinaryPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BinaryPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BinaryPayload) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_binarypayload_proto protoreflect.FileDescriptor

const file_binarypayload_proto_rawDesc = "" +
	"\n" +
	"\x13binarypayload.proto\x12\x0fgoatak.cotproto\"\x83\x01\n" +
	"\rBinaryPayload\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuidB&H\x03Z\"github.com/kdudkov/goatak/cotprotob\x06proto3"

var (
	file_binarypayload_proto_rawDescOnce sync.Once
	file_binarypayload_proto_rawDescData []byte
)

func file_binarypayload_proto_rawDescGZIP() []byte {
	file_binarypayload_proto_rawDescOnce.Do(func() {
		file_binarypayload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_binarypayload_proto_rawDesc), len(file_binarypayload_proto_rawDesc)))
	})
	return file_binarypayload_proto_rawDescData
}

var file_binarypayload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_binarypayload_proto_goTypes = []any{
	(*BinaryPayload)(nil), // 0: goatak.cotproto.BinaryPayload
}
var file_binarypayload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_binarypayload_proto_init() }
func file_binarypayload_proto_init() {
	if File_binarypayload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_binarypayload_proto_rawDesc), len(file_binarypayload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_binarypayload_proto_goTypes,
		DependencyIndexes: file_binarypayload_proto_depIdxs,
		MessageInfos:      file_binarypayload_proto_msgTypes,
	}.Build()
	File_binarypayload_proto = out.File
	file_binarypayload_proto_goTypes = nil
	file_binarypayload_proto_depIdxs = nil
}
