// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: binarypayload.proto

package cotproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`            // type identifier for the BinaryPayload. Use this type to determine decoding strategy
	Version   string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`      // version identifier for the binary message
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`            // binary message payload data
	Timestamp int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // timestamp when ingested
	Uuid      string `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`            // unique id for this BinaryPayload
}

func (x *BinaryPayload) Reset() {
	*x = BinaryPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_binarypayload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinaryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryPayload) ProtoMessage() {}

func (x *BinaryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_binarypayload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryPayload.ProtoReflect.Descriptor instead.
func (*BinaryPayload) Descriptor() ([]byte, []int) {
	return file_binarypayload_proto_rawDescGZIP(), []int{0}
}

func (x *BinaryPayload) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BinaryPayload) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BinaryPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BinaryPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BinaryPayload) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_binarypayload_proto protoreflect.FileDescriptor

var file_binarypayload_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x0d, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x42, 0x26, 0x48, 0x03, 0x5a,
	0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x64, 0x75, 0x64,
	0x6b, 0x6f, 0x76, 0x2f, 0x67, 0x6f, 0x61, 0x74, 0x61, 0x6b, 0x2f, 0x63, 0x6f, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_binarypayload_proto_rawDescOnce sync.Once
	file_binarypayload_proto_rawDescData = file_binarypayload_proto_rawDesc
)

func file_binarypayload_proto_rawDescGZIP() []byte {
	file_binarypayload_proto_rawDescOnce.Do(func() {
		file_binarypayload_proto_rawDescData = protoimpl.X.CompressGZIP(file_binarypayload_proto_rawDescData)
	})
	return file_binarypayload_proto_rawDescData
}

var file_binarypayload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_binarypayload_proto_goTypes = []interface{}{
	(*BinaryPayload)(nil), // 0: BinaryPayload
}
var file_binarypayload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_binarypayload_proto_init() }
func file_binarypayload_proto_init() {
	if File_binarypayload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_binarypayload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BinaryPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_binarypayload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_binarypayload_proto_goTypes,
		DependencyIndexes: file_binarypayload_proto_depIdxs,
		MessageInfos:      file_binarypayload_proto_msgTypes,
	}.Build()
	File_binarypayload_proto = out.File
	file_binarypayload_proto_rawDesc = nil
	file_binarypayload_proto_goTypes = nil
	file_binarypayload_proto_depIdxs = nil
}
