// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: detail.proto

package cotproto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Detail struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	XmlDetail string                 `protobuf:"bytes,1,opt,name=xmlDetail,proto3" json:"xmlDetail,omitempty"`
	// <contact>
	Contact *Contact `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	// <__group>
	Group *Group `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	// <precisionlocation>
	PrecisionLocation *PrecisionLocation `protobuf:"bytes,4,opt,name=precisionLocation,proto3" json:"precisionLocation,omitempty"`
	// <status>
	Status *Status `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// <takv>
	Takv *Takv `protobuf:"bytes,6,opt,name=takv,proto3" json:"takv,omitempty"`
	// <track>
	Track         *Track `protobuf:"bytes,7,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail) Reset() {
	*x = Detail{}
	mi := &file_detail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail) ProtoMessage() {}

func (x *Detail) ProtoReflect() protoreflect.Message {
	mi := &file_detail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail.ProtoReflect.Descriptor instead.
func (*Detail) Descriptor() ([]byte, []int) {
	return file_detail_proto_rawDescGZIP(), []int{0}
}

func (x *Detail) GetXmlDetail() string {
	if x != nil {
		return x.XmlDetail
	}
	return ""
}

func (x *Detail) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Detail) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *Detail) GetPrecisionLocation() *PrecisionLocation {
	if x != nil {
		return x.PrecisionLocation
	}
	return nil
}

func (x *Detail) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Detail) GetTakv() *Takv {
	if x != nil {
		return x.Takv
	}
	return nil
}

func (x *Detail) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

var File_detail_proto protoreflect.FileDescriptor

const file_detail_proto_rawDesc = "" +
	"\n" +
	"\fdetail.proto\x12\x0fgoatak.cotproto\x1a\rcontact.proto\x1a\vgroup.proto\x1a\x17precisionlocation.proto\x1a\fstatus.proto\x1a\n" +
	"takv.proto\x1a\vtrack.proto\"\xe4\x02\n" +
	"\x06Detail\x12\x1c\n" +
	"\txmlDetail\x18\x01 \x01(\tR\txmlDetail\x122\n" +
	"\acontact\x18\x02 \x01(\v2\x18.goatak.cotproto.ContactR\acontact\x12,\n" +
	"\x05group\x18\x03 \x01(\v2\x16.goatak.cotproto.GroupR\x05group\x12P\n" +
	"\x11precisionLocation\x18\x04 \x01(\v2\".goatak.cotproto.PrecisionLocationR\x11precisionLocation\x12/\n" +
	"\x06status\x18\x05 \x01(\v2\x17.goatak.cotproto.StatusR\x06status\x12)\n" +
	"\x04takv\x18\x06 \x01(\v2\x15.goatak.cotproto.TakvR\x04takv\x12,\n" +
	"\x05track\x18\a \x01(\v2\x16.goatak.cotproto.TrackR\x05trackB&H\x03Z\"github.com/kdudkov/goatak/cotprotob\x06proto3"

var (
	file_detail_proto_rawDescOnce sync.Once
	file_detail_proto_rawDescData []byte
)

func file_detail_proto_rawDescGZIP() []byte {
	file_detail_proto_rawDescOnce.Do(func() {
		file_detail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_detail_proto_rawDesc), len(file_detail_proto_rawDesc)))
	})
	return file_detail_proto_rawDescData
}

var file_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_detail_proto_goTypes = []any{
	(*Detail)(nil),            // 0: goatak.cotproto.Detail
	(*Contact)(nil),           // 1: goatak.cotproto.Contact
	(*Group)(nil),             // 2: goatak.cotproto.Group
	(*PrecisionLocation)(nil), // 3: goatak.cotproto.PrecisionLocation
	(*Status)(nil),            // 4: goatak.cotproto.Status
	(*Takv)(nil),              // 5: goatak.cotproto.Takv
	(*Track)(nil),             // 6: goatak.cotproto.Track
}
var file_detail_proto_depIdxs = []int32{
	1, // 0: goatak.cotproto.Detail.contact:type_name -> goatak.cotproto.Contact
	2, // 1: goatak.cotproto.Detail.group:type_name -> goatak.cotproto.Group
	3, // 2: goatak.cotproto.Detail.precisionLocation:type_name -> goatak.cotproto.PrecisionLocation
	4, // 3: goatak.cotproto.Detail.status:type_name -> goatak.cotproto.Status
	5, // 4: goatak.cotproto.Detail.takv:type_name -> goatak.cotproto.Takv
	6, // 5: goatak.cotproto.Detail.track:type_name -> goatak.cotproto.Track
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_detail_proto_init() }
func file_detail_proto_init() {
	if File_detail_proto != nil {
		return
	}
	file_contact_proto_init()
	file_group_proto_init()
	file_precisionlocation_proto_init()
	file_status_proto_init()
	file_takv_proto_init()
	file_track_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_detail_proto_rawDesc), len(file_detail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_detail_proto_goTypes,
		DependencyIndexes: file_detail_proto_depIdxs,
		MessageInfos:      file_detail_proto_msgTypes,
	}.Build()
	File_detail_proto = out.File
	file_detail_proto_goTypes = nil
	file_detail_proto_depIdxs = nil
}
