// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: message.proto

package cotproto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Container for TakMessage and metadata, such as groups
type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Payload        *TakMessage            `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Source         string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ClientId       string                 `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Groups         []string               `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	DestClientUids []string               `protobuf:"bytes,5,rep,name=destClientUids,proto3" json:"destClientUids,omitempty"`
	DestCallsigns  []string               `protobuf:"bytes,6,rep,name=destCallsigns,proto3" json:"destCallsigns,omitempty"`
	Provenance     []string               `protobuf:"bytes,7,rep,name=provenance,proto3" json:"provenance,omitempty"`
	Archive        bool                   `protobuf:"varint,8,opt,name=archive,proto3" json:"archive,omitempty"`
	FeedUuid       string                 `protobuf:"bytes,9,opt,name=feedUuid,proto3" json:"feedUuid,omitempty"`
	ConnectionId   string                 `protobuf:"bytes,10,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	// optional sequence of binary payloads
	Bloads        []*BinaryPayload `protobuf:"bytes,11,rep,name=bloads,proto3" json:"bloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetPayload() *TakMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Message) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Message) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Message) GetDestClientUids() []string {
	if x != nil {
		return x.DestClientUids
	}
	return nil
}

func (x *Message) GetDestCallsigns() []string {
	if x != nil {
		return x.DestCallsigns
	}
	return nil
}

func (x *Message) GetProvenance() []string {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *Message) GetArchive() bool {
	if x != nil {
		return x.Archive
	}
	return false
}

func (x *Message) GetFeedUuid() string {
	if x != nil {
		return x.FeedUuid
	}
	return ""
}

func (x *Message) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Message) GetBloads() []*BinaryPayload {
	if x != nil {
		return x.Bloads
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x0fgoatak.cotproto\x1a\x10takmessage.proto\x1a\x13binarypayload.proto\"\x8c\x03\n" +
	"\aMessage\x125\n" +
	"\apayload\x18\x01 \x01(\v2\x1b.goatak.cotproto.TakMessageR\apayload\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1a\n" +
	"\bclientId\x18\x03 \x01(\tR\bclientId\x12\x16\n" +
	"\x06groups\x18\x04 \x03(\tR\x06groups\x12&\n" +
	"\x0edestClientUids\x18\x05 \x03(\tR\x0edestClientUids\x12$\n" +
	"\rdestCallsigns\x18\x06 \x03(\tR\rdestCallsigns\x12\x1e\n" +
	"\n" +
	"provenance\x18\a \x03(\tR\n" +
	"provenance\x12\x18\n" +
	"\aarchive\x18\b \x01(\bR\aarchive\x12\x1a\n" +
	"\bfeedUuid\x18\t \x01(\tR\bfeedUuid\x12\"\n" +
	"\fconnectionId\x18\n" +
	" \x01(\tR\fconnectionId\x126\n" +
	"\x06bloads\x18\v \x03(\v2\x1e.goatak.cotproto.BinaryPayloadR\x06bloadsB&H\x03Z\"github.com/kdudkov/goatak/cotprotob\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_proto_goTypes = []any{
	(*Message)(nil),       // 0: goatak.cotproto.Message
	(*TakMessage)(nil),    // 1: goatak.cotproto.TakMessage
	(*BinaryPayload)(nil), // 2: goatak.cotproto.BinaryPayload
}
var file_message_proto_depIdxs = []int32{
	1, // 0: goatak.cotproto.Message.payload:type_name -> goatak.cotproto.TakMessage
	2, // 1: goatak.cotproto.Message.bloads:type_name -> goatak.cotproto.BinaryPayload
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_takmessage_proto_init()
	file_binarypayload_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
