// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: missionannouncement.proto

package cotproto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Container for MissionAnnouncement and metadata
type MissionAnnouncement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload                 *TakMessage `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	MissionName             string      `protobuf:"bytes,2,opt,name=missionName,proto3" json:"missionName,omitempty"`
	MissionAnnouncementType string      `protobuf:"bytes,3,opt,name=missionAnnouncementType,proto3" json:"missionAnnouncementType,omitempty"`
	CreatorUid              string      `protobuf:"bytes,4,opt,name=creatorUid,proto3" json:"creatorUid,omitempty"`
	GroupVector             string      `protobuf:"bytes,5,opt,name=groupVector,proto3" json:"groupVector,omitempty"`
	ClientUid               string      `protobuf:"bytes,6,opt,name=clientUid,proto3" json:"clientUid,omitempty"`
	Uids                    []string    `protobuf:"bytes,7,rep,name=uids,proto3" json:"uids,omitempty"`
}

func (x *MissionAnnouncement) Reset() {
	*x = MissionAnnouncement{}

	if protoimpl.UnsafeEnabled {
		mi := &file_missionannouncement_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MissionAnnouncement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionAnnouncement) ProtoMessage() {}

func (x *MissionAnnouncement) ProtoReflect() protoreflect.Message {
	mi := &file_missionannouncement_proto_msgTypes[0]

	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}

		return ms
	}

	return mi.MessageOf(x)
}

// Deprecated: Use MissionAnnouncement.ProtoReflect.Descriptor instead.
func (*MissionAnnouncement) Descriptor() ([]byte, []int) {
	return file_missionannouncement_proto_rawDescGZIP(), []int{0}
}

func (x *MissionAnnouncement) GetPayload() *TakMessage {
	if x != nil {
		return x.Payload
	}

	return nil
}

func (x *MissionAnnouncement) GetMissionName() string {
	if x != nil {
		return x.MissionName
	}

	return ""
}

func (x *MissionAnnouncement) GetMissionAnnouncementType() string {
	if x != nil {
		return x.MissionAnnouncementType
	}

	return ""
}

func (x *MissionAnnouncement) GetCreatorUid() string {
	if x != nil {
		return x.CreatorUid
	}

	return ""
}

func (x *MissionAnnouncement) GetGroupVector() string {
	if x != nil {
		return x.GroupVector
	}

	return ""
}

func (x *MissionAnnouncement) GetClientUid() string {
	if x != nil {
		return x.ClientUid
	}

	return ""
}

func (x *MissionAnnouncement) GetUids() []string {
	if x != nil {
		return x.Uids
	}

	return nil
}

var File_missionannouncement_proto protoreflect.FileDescriptor

var file_missionannouncement_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x74, 0x61, 0x6b,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x02,
	0x0a, 0x13, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x61, 0x6b, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38,
	0x0a, 0x17, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x17, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x55, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x55, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x55, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x42, 0x26, 0x48, 0x03,
	0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x64, 0x75,
	0x64, 0x6b, 0x6f, 0x76, 0x2f, 0x67, 0x6f, 0x61, 0x74, 0x61, 0x6b, 0x2f, 0x63, 0x6f, 0x74, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_missionannouncement_proto_rawDescOnce sync.Once
	file_missionannouncement_proto_rawDescData = file_missionannouncement_proto_rawDesc
)

func file_missionannouncement_proto_rawDescGZIP() []byte {
	file_missionannouncement_proto_rawDescOnce.Do(func() {
		file_missionannouncement_proto_rawDescData = protoimpl.X.CompressGZIP(file_missionannouncement_proto_rawDescData)
	})

	return file_missionannouncement_proto_rawDescData
}

var file_missionannouncement_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_missionannouncement_proto_goTypes = []interface{}{
	(*MissionAnnouncement)(nil), // 0: MissionAnnouncement
	(*TakMessage)(nil),          // 1: TakMessage
}
var file_missionannouncement_proto_depIdxs = []int32{
	1, // 0: MissionAnnouncement.payload:type_name -> TakMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_missionannouncement_proto_init() }
func file_missionannouncement_proto_init() {
	if File_missionannouncement_proto != nil {
		return
	}

	file_takmessage_proto_init()

	if !protoimpl.UnsafeEnabled {
		file_missionannouncement_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MissionAnnouncement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}

	type x struct{}

	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_missionannouncement_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_missionannouncement_proto_goTypes,
		DependencyIndexes: file_missionannouncement_proto_depIdxs,
		MessageInfos:      file_missionannouncement_proto_msgTypes,
	}.Build()
	File_missionannouncement_proto = out.File
	file_missionannouncement_proto_rawDesc = nil
	file_missionannouncement_proto_goTypes = nil
	file_missionannouncement_proto_depIdxs = nil
}
