// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: precisionlocation.proto

package cotproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// All items are required unless otherwise noted!
// "required" means if they are missing on send, the conversion
// to the message format will be rejected and fall back to opaque
// XML representation
type PrecisionLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geopointsrc   string                 `protobuf:"bytes,1,opt,name=geopointsrc,proto3" json:"geopointsrc,omitempty"` // geopointsrc=
	Altsrc        string                 `protobuf:"bytes,2,opt,name=altsrc,proto3" json:"altsrc,omitempty"`           // altsrc=
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrecisionLocation) Reset() {
	*x = PrecisionLocation{}
	mi := &file_precisionlocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrecisionLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecisionLocation) ProtoMessage() {}

func (x *PrecisionLocation) ProtoReflect() protoreflect.Message {
	mi := &file_precisionlocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecisionLocation.ProtoReflect.Descriptor instead.
func (*PrecisionLocation) Descriptor() ([]byte, []int) {
	return file_precisionlocation_proto_rawDescGZIP(), []int{0}
}

func (x *PrecisionLocation) GetGeopointsrc() string {
	if x != nil {
		return x.Geopointsrc
	}
	return ""
}

func (x *PrecisionLocation) GetAltsrc() string {
	if x != nil {
		return x.Altsrc
	}
	return ""
}

var File_precisionlocation_proto protoreflect.FileDescriptor

const file_precisionlocation_proto_rawDesc = "" +
	"\n" +
	"\x17precisionlocation.proto\x12\x0fgoatak.cotproto\"M\n" +
	"\x11PrecisionLocation\x12 \n" +
	"\vgeopointsrc\x18\x01 \x01(\tR\vgeopointsrc\x12\x16\n" +
	"\x06altsrc\x18\x02 \x01(\tR\x06altsrcB&H\x03Z\"github.com/kdudkov/goatak/cotprotob\x06proto3"

var (
	file_precisionlocation_proto_rawDescOnce sync.Once
	file_precisionlocation_proto_rawDescData []byte
)

func file_precisionlocation_proto_rawDescGZIP() []byte {
	file_precisionlocation_proto_rawDescOnce.Do(func() {
		file_precisionlocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_precisionlocation_proto_rawDesc), len(file_precisionlocation_proto_rawDesc)))
	})
	return file_precisionlocation_proto_rawDescData
}

var file_precisionlocation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_precisionlocation_proto_goTypes = []any{
	(*PrecisionLocation)(nil), // 0: goatak.cotproto.PrecisionLocation
}
var file_precisionlocation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_precisionlocation_proto_init() }
func file_precisionlocation_proto_init() {
	if File_precisionlocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_precisionlocation_proto_rawDesc), len(file_precisionlocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_precisionlocation_proto_goTypes,
		DependencyIndexes: file_precisionlocation_proto_depIdxs,
		MessageInfos:      file_precisionlocation_proto_msgTypes,
	}.Build()
	File_precisionlocation_proto = out.File
	file_precisionlocation_proto_goTypes = nil
	file_precisionlocation_proto_depIdxs = nil
}
