// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: cotevent.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// this seems to be used for all CoT sent from ATAK
// A note about timestamps:
// Uses "timeMs" units, which is number of milliseconds since
// 1970-01-01 00:00:00 UTC
//
// All items are required unless otherwise noted!
// "required" means if they are missing in the XML during outbound
// conversion to protobuf, the message will be
// rejected
type CotEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`            // <event type="x">
	Access    string `protobuf:"bytes,2,opt,name=access,proto3" json:"access,omitempty"`        // optional
	Qos       string `protobuf:"bytes,3,opt,name=qos,proto3" json:"qos,omitempty"`              // optional
	Opex      string `protobuf:"bytes,4,opt,name=opex,proto3" json:"opex,omitempty"`            // optional
	Uid       string `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`              // <event uid="x">
	SendTime  uint64 `protobuf:"varint,6,opt,name=sendTime,proto3" json:"sendTime,omitempty"`   // <event time="x"> converted to timeMs
	StartTime uint64 `protobuf:"varint,7,opt,name=startTime,proto3" json:"startTime,omitempty"` // <event start="x"> converted to timeMs
	StaleTime uint64 `protobuf:"varint,8,opt,name=staleTime,proto3" json:"staleTime,omitempty"` // <event stale="x"> converted to timeMs
	How       string `protobuf:"bytes,9,opt,name=how,proto3" json:"how,omitempty"`              // <event how="x">
	// <point>
	Lat float64 `protobuf:"fixed64,10,opt,name=lat,proto3" json:"lat,omitempty"` // <point lat="x">
	Lon float64 `protobuf:"fixed64,11,opt,name=lon,proto3" json:"lon,omitempty"` // <point lon="x">
	Hae float64 `protobuf:"fixed64,12,opt,name=hae,proto3" json:"hae,omitempty"` // <point hae="x"> use 999999 for unknown
	Ce  float64 `protobuf:"fixed64,13,opt,name=ce,proto3" json:"ce,omitempty"`   // <point ce="x"> use 999999 for unknown
	Le  float64 `protobuf:"fixed64,14,opt,name=le,proto3" json:"le,omitempty"`   // <point ce="x"> use 999999 for unknown
	// comprises children of <detail>
	// This is optional - if omitted, then the cot message
	// had no data under <detail>
	Detail *Detail `protobuf:"bytes,15,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *CotEvent) Reset() {
	*x = CotEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cotevent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CotEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CotEvent) ProtoMessage() {}

func (x *CotEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cotevent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CotEvent.ProtoReflect.Descriptor instead.
func (*CotEvent) Descriptor() ([]byte, []int) {
	return file_cotevent_proto_rawDescGZIP(), []int{0}
}

func (x *CotEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CotEvent) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *CotEvent) GetQos() string {
	if x != nil {
		return x.Qos
	}
	return ""
}

func (x *CotEvent) GetOpex() string {
	if x != nil {
		return x.Opex
	}
	return ""
}

func (x *CotEvent) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CotEvent) GetSendTime() uint64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *CotEvent) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CotEvent) GetStaleTime() uint64 {
	if x != nil {
		return x.StaleTime
	}
	return 0
}

func (x *CotEvent) GetHow() string {
	if x != nil {
		return x.How
	}
	return ""
}

func (x *CotEvent) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *CotEvent) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *CotEvent) GetHae() float64 {
	if x != nil {
		return x.Hae
	}
	return 0
}

func (x *CotEvent) GetCe() float64 {
	if x != nil {
		return x.Ce
	}
	return 0
}

func (x *CotEvent) GetLe() float64 {
	if x != nil {
		return x.Le
	}
	return 0
}

func (x *CotEvent) GetDetail() *Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

var File_cotevent_proto protoreflect.FileDescriptor

var file_cotevent_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6f, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcf,
	0x02, 0x0a, 0x08, 0x43, 0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x6f, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x71, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x78, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x6f, 0x77, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x68, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x68, 0x61, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x68, 0x61, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x63, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x6c, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x6c, 0x65, 0x12,
	0x1f, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b,
	0x64, 0x75, 0x64, 0x6b, 0x6f, 0x76, 0x2f, 0x67, 0x6f, 0x61, 0x74, 0x61, 0x6b, 0x2f, 0x63, 0x6f,
	0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cotevent_proto_rawDescOnce sync.Once
	file_cotevent_proto_rawDescData = file_cotevent_proto_rawDesc
)

func file_cotevent_proto_rawDescGZIP() []byte {
	file_cotevent_proto_rawDescOnce.Do(func() {
		file_cotevent_proto_rawDescData = protoimpl.X.CompressGZIP(file_cotevent_proto_rawDescData)
	})
	return file_cotevent_proto_rawDescData
}

var file_cotevent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cotevent_proto_goTypes = []interface{}{
	(*CotEvent)(nil), // 0: CotEvent
	(*Detail)(nil),   // 1: Detail
}
var file_cotevent_proto_depIdxs = []int32{
	1, // 0: CotEvent.detail:type_name -> Detail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cotevent_proto_init() }
func file_cotevent_proto_init() {
	if File_cotevent_proto != nil {
		return
	}
	file_detail_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cotevent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CotEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cotevent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cotevent_proto_goTypes,
		DependencyIndexes: file_cotevent_proto_depIdxs,
		MessageInfos:      file_cotevent_proto_msgTypes,
	}.Build()
	File_cotevent_proto = out.File
	file_cotevent_proto_rawDesc = nil
	file_cotevent_proto_goTypes = nil
	file_cotevent_proto_depIdxs = nil
}
