package mp

import "fmt"

type PrefKey struct {
	Name   string
	Key    string
	Cls    string
	Values string
}

var prefKeys = []PrefKey{
	{"My Callsign", "locationCallsign", "String", "Alphanumeric"},
	{"My Team", "locationTeam", "String", "White; Yellow; Orange; Magenta; Red; Maroon; Purple; Dark Blue; Blue; Cyan; Teal; Green; Dark Green; Brown"},
	{"My Role", "atakRoleType", "String", "Team Member; Team Lead; HQ; Sniper; Medic; Forward Observer; RTO; K9"},
	{"My Display Type", "locationUnitType", "String", "Ground Troop; Armored Vehicle; Civilian Vehicle; Generic Air Unit; Generic Ground Unit; Generic Sea Surface Unit"},
	{"GPS Option", "mockingOption", "String", "IgnoreInternalGPS = Ignore Internal GPS / Use External or Network GPS Only; LocalGPS = Internal GPS Only; WRGPS = External or Network GPS / Fallback Internal GPS"},
	{"Network GPS Port", "listenPort", "String", "0 - 65535 (Default 4349)"},
	{"Use GPS Time", "useGPSTime", "Boolean", "true; false"},
	{"Use Elevation Data instead of GPS Elevation", "useTerrainElevationSelfMarker", "Boolean", ""},
	{"Non-Bluetooth Laser Range Finders Support", "nonBluetoothLaserRangeFinder", "Boolean", ""},
	{"Use Wave Relay Callsign", "locationUseWRCallsign", "Boolean", ""},
	{"Bluetooth Support", "atakControlBluetooth", "Boolean", ""},
	{"Bluetooth Reconnect Time", "atakBluetoothReconnectSeconds", "String", "Numeric"},
	{"Publish Phone Number", "saHasPhoneNumber", "Boolean", ""},
	{"Publish VoIP Number", "saSipAddressAssignment", "String", "Alphanumeric"},
	{"VoIP Number", "saSipAddress", "String", "No VOIP; Manual Entry; Use IP Address; Use Callsign and IP Address"},
	{"Publish XMPP Username", "saXmppUsername", "String", "Alphanumeric"},
	{"Publish Preferred Email", "saEmailAddress", "String", "Alphanumeric"},
	{"Unit Reference Number", "saURN", "String", "0 - 16777215"},
	{"Send Location Over Network", "dispatchLocationCotExternal", "Boolean", ""},
	{"Hide my current position", "dispatchLocationHidden", "Boolean", ""},
	{"Reporting Strategy", "locationReportingStrategy", "String", "Dynamic; Constant"},
	{"Dynamic Reporting Rate Stationary (Unreliable)", "dynamicReportingRateStationaryUnreliable", "String", "Numeric"},
	{"Dynamic Reporting Rate Minimum (Unreliable)", "dynamicReportingRateMinUnreliable", "String", "Numeric"},
	{"Dynamic Reporting Rate Maximum (Unreliable)", "dynamicReportingRateMaxUnreliable", "String", "Numeric"},
	{"Dynamic Reporting Rate Stationary (Reliable)", "dynamicReportingRateStationaryReliable", "String", "Numeric"},
	{"Dynamic Reporting Rate Minimum (Reliable)", "dynamicReportingRateMinReliable", "String", "Numeric"},
	{"Dynamic Reporting Rate Maximum (Reliable)", "dynamicReportingRateMaxReliable", "String", "Numeric"},
	{"Constant Reporting Rate (Unreliable)", "constantReportingRateUnreliable", "String", "Numeric"},
	{"Constant Reporting Rate (Reliable)", "constantReportingRateReliable", "String", "Numeric"},
	{"Report Location before obtaining location fix", "dispatchLocationCotExternalAtStart", "Boolean", ""},
	{"Change Encryption Passphrase", "encryptionPassphrase", "String", "Alphanumeric"},
	{"Display Connection Widget", "displayServerConnectionWidget", "Boolean", ""},
	{"Monitor Server Connections", "monitorServerConnections", "Boolean", ""},
	{"Default SSL/TLS TrustStore Location", "caLocation", "String", "Alphanumeric"},
	{"Default SSL/TLS TrustStore Password", "caPassword", "String", "Alphanumeric"},
	{"Default SSL/TLS Client Certificate Store", "certificateLocation", "String", "Alphanumeric"},
	{"Default SSL/TLS Client Certificate Password", "clientPassword", "String", "Alphanumeric"},
	{"Default SSL/TLS Credentials", "default_client_credentials", "String", "Alphanumeric"},
	{"Secure Server API port", "apiSecureServerPort", "String", "0-65535"},
	{"Unsecure Server API port", "apiUnsecureServerPort", "String", "0-65535"},
	{"Certificate Enrollment API port", "apiCertEnrollmentPort", "String", "0-65535"},
	{"Certificate Enrollment Key Length", "apiCertEnrollmentKeyLength", "String", "Numeric"},
	{"Enable Client Certificate Export", "certEnrollmentExport", "Boolean", ""},
	{"Apply TAK Server profile updates", "deviceProfileEnableOnConnect", "Boolean", ""},
	{"Enable Mesh Network Mode", "enableNonStreamingConnections", "Boolean", ""},
	{"Auto Manage Mesh Network Self SA Mode", "autoDisableMeshSAWhenStreaming", "Boolean", ""},
	{"TCP Connection Timeout", "tcpConnectTimeout", "String", "Numeric"},
	{"Multicast Network Rejoin interval", "udpNoDataTimeout", "String", "Numeric"},
	{"Multicast TTL", "multicastTTL", "String", "Numeric"},
	{"Multicast Traffic Loopback", "network_multicast_loopback", "Boolean", ""},
	{"Point-to-Point Link High Speed Capable", "ppp0_highspeed_capable", "Boolean", ""},
	{"Legacy Wave Relay Redirect", "waveRelayRedirect", "Boolean", ""},
	{"Enable VPN Proxy Mode", "httpClientPermissiveMode", "Boolean", ""},
	{"Auto Start on Placement", "autostart_nineline", "Boolean", ""},
	{"Auto Start Menu", "autostart_nineline_type", "String", "cas; cff"},
	{"Danger Close Coloring", "prone_standing_coloring", "Boolean", ""},
	{"Use Keyhole CAS", "keyhole_cas", "Boolean", ""},
	{"FAH Distance (NM)", "fahDistance", "String", "0-21600"},
	{"Default FAH Width", "fahWidth", "String", "0-180"},
	{"Automatically Display FAH", "fahOnCreation", "Boolean", ""},
	{"Automatically Display Reciprocal FAH", "fahReciprocalOnCreation", "Boolean", ""},
	{"Laser Basket Distance (NM)", "laserBasketDistance", "String", "0-21600"},
	{"Laser Basket Measurements", "laserBasketDegrees", "Boolean", ""},
	{"FAH Always Edit Mode", "nineline_fah_edit_always", "Boolean", ""},
	{"Enable Address Lookup (Geocoder)", "enableGeocoder", "Boolean", ""},
	{"Address Provider", "selected_geocoder_uid", "String", "android-geocoder"},
	{"Notification", "alert_notification", "Boolean", ""},
	{"Individual Alert Notifications", "individual_alert_notification", "Boolean", ""},
	{"Audible alert", "alert_audible", "Boolean", ""},
	{"Vibration alert", "alert_vibration", "Boolean", ""},
	{"Alert SMS Numbers", "sms_numbers", "String", "Numeric 11-15 digits"},
	{"Display Bloodhound Text Widget", "rab_bloodhound_display_textwidget", "Boolean", ""},
	{"Display Large Bloodhound Text Widget", "rab_bloodhound_large_textwidget", "Boolean", ""},
	{"Flash When Closing In", "rab_bloodhound_flash_colors", "Boolean", ""},
	{"Toggle Auto Zoom", "rab_bloodhound_zoom", "Boolean", ""},
	{"Flash ETA Threshold", "bloodhound_flash_eta", "String", "Numeric"},
	{"Outer/Middle ETA Threshold", "bloodhound_outer_eta", "String", "Numeric"},
	{"Middle/Inner ETA Threshold", "bloodhound_inner_eta", "String", "Numeric"},
	{"Flash Color", "bloodhound_flash_color_pref", "String", "red; yellow; green; cyan; blue; magenta; white; black"},
	{"Outer ETA Color", "bloodhound_outer_color_pref", "String", ""},
	{"Middle ETA Color", "bloodhound_middle_color_pref", "String", ""},
	{"Inner ETA Color", "bloodhound_inner_color_pref", "String", ""},
	{"Reroute distance", "bloodhound_reroute_distance_pref", "String", "Numeric"},
	{"Reroute timer frequency", "bloodhound_reroute_timer_pref", "String", "Numeric"},
	{"Display Notification", "enableToast", "Boolean", ""},
	{"Vibrate phone", "vibratePhone", "Boolean", ""},
	{"Audible Chat notifications", "audibleNotify", "Boolean", ""},
	{"Chat Address", "chatAddress", "String", "1.1.1.1 - 255.255.255.255"},
	{"Chat Port", "chatPort", "String", "0-65535"},
	{"Enable file sharing.", "filesharingEnabled", "Boolean", ""},
	{"File Transfer Max size", "filesharingSizeThresholdNoGo", "String", "Numeric"},
	{"Download attempts", "fileshareDownloadAttempts", "String", "Numeric"},
	{"Allow HTTP transfers", "filesharingWebServerLegacyHttpEnabled", "Boolean", ""},
	{"Server port", "filesharingWebServerPort", "String", "0-65535"},
	{"Secure Server port", "filesharingSecureWebServerPort", "String", "0-65535"},
	{"File Transfer Connection Timeout", "filesharingConnectionTimeoutSecs", "String", "Numeric"},
	{"File Transfer Failure Timeout", "filesharingTransferTimeoutSecs", "String", "Numeric"},
	{"Use All Servers", "filesharingAllServers", "Boolean", ""},
	{"Elevation Server", "prefs_dted_stream_server", "String", "Alphanumeric"},
	{"Stream Elevation Data", "prefs_dted_stream", "Boolean", ""},
	{"Show by Default", "prefs_dted_visible", "Boolean", ""},
	{"Rapid MGRS Entry Mode", "rapid_mgrs_dialog", "Boolean", ""},
	{"DP/SPI Update Period", "spiUpdateDelay", "String", "Numeric"},
	{"Automatically Broadcast a Marker", "hostileUpdateDelay", "String", "0; 60; 90; 120"},
	{"Legacy Toolbar Mode", "legacyFiresToolbarMode", "Boolean", ""},
	{"Number of DP/SPIs", "firesNumberOfSpis", "String", "1; 2; 3"},
	{"DP/RedX FAH Width", "spiFahSize", "String", "0-180"},
	{"Expanded Danger Close Search", "expandedDangerClose", "Boolean", ""},
	{"WMS Connect Timeout", "wms_connect_timeout", "Integer", "3000; 5000; 10000; 15000; 30000"},
	{"Enable Volume Keys rotating map layers", "volumemapswitcher", "Boolean", ""},
	{"Enable Image Overlay Map Interaction", "prefs_layer_grg_map_interaction", "Boolean", ""},
	{"Collect Metrics", "collect_metrics", "Boolean", ""},
	{"Live Metrics", "realtime_metrics", "Boolean", ""},
	{"Advanced CoT Recorder", "generate_full_pool", "Boolean", ""},
	{"Advanced CoT Details Recorder", "generate_detail_pool", "Boolean", ""},
	{"Checkpoint Name Prefix", "waypointPrefix", "String", "Alphanumeric"},
	{"Default for unspecified Route Colors", "defaultRouteColor", "String", "-1 through -16777216"},
	{"Traditional Navigation Mode", "route_track_up_locked_on", "Boolean", ""},
	{"Navigational Voice Cues", "useRouteVoiceCues", "Boolean", ""},
	{"Vibrate When Arriving at Checkpoint", "route_vibrate_at_checkpoint", "Boolean", ""},
	{"Walking Checkpoint Navigation Bubble Radius", "waypointBubble.Walking", "String", "Numeric"},
	{"Walking Off Route Bubble Radius", "waypointOffRouteBubble.Walking", "String", "Numeric"},
	{"Driving Checkpoint Navigation Bubble Radius", "waypointBubble.Driving", "String", "Numeric"},
	{"Driving Off Route Bubble Radius", "waypointOffRouteBubble.Driving", "String", "Numeric"},
	{"Flying Checkpoint Navigation Bubble Radius", "waypointBubble.Flying", "String", "Numeric"},
	{"Flying Off Route Bubble Radius", "waypointOffRouteBubble.Flying", "String", "Numeric"},
	{"Swimming Checkpoint Navigation Bubble Radius", "waypointBubble.Swimming", "String", "Numeric"},
	{"Swimming Off Route Bubble Radius", "waypointOffRouteBubble.Swimming", "String", "Numeric"},
	{"Watercraft Checkpoint Navigation Bubble Radius", "waypointBubble.Watercraft", "String", "Numeric"},
	{"Watercraft Off Route Bubble Radius", "waypointOffRouteBubble.Watercraft", "String", "Numeric"},
	{"Show Attachment Billboards", "route_billboard_enabled", "Boolean", ""},
	{"Billboard Render Distance", "route_billboard_distance_m", "String", "Numeric"},
	{"Elevation Profile Interpolate Altitudes", "elevProfileInterpolateAlt", "Boolean", ""},
	{"Elevation Profile Center on Seeker", "elevProfileCenterOnSeeker", "Boolean", ""},
	{"GPX Import Checkpoints", "gpxImportCheckpointsForNamedRoutePoints", "Boolean", ""},
	{"Ignore Elevation Data", "kmlExportGroundClamp", "Boolean", ""},
	{"KML Export Checkpoint Mode", "kmlExportCheckpointMode", "String", "Points; Line; Both"},
	{"Internal Network Configuration", "network_config", "Boolean", ""},
	{"DHCP", "network_dhcp", "Boolean", ""},
	{"IP address", "network_static_ip_address", "String", "1.1.1.1 - 255.255.255.255"},
	{"Subnet mask", "network_static_subnet_mask", "String", "1.1.1.1 - 255.255.255.255"},
	{"Default gateway", "network_static_gateway", "String", "1.1.1.1 - 255.255.255.255"},
	{"DNS 1", "network_static_dns1", "String", "1.1.1.1 - 255.255.255.255"},
	{"DNS 2", "network_static_dns2", "String", "1.1.1.1 - 255.255.255.255"},
	{"Log Tracks", "toggle_log_tracks", "Boolean", ""},
	{"Track Prefix", "track_prefix", "String", "Alphanumeric"},
	{"Auto Rotate Track Colors", "toggle_rotate_track_colors", "Boolean", ""},
	{"Default Color", "track_history_default_color", "String", "-1 through -16777216"},
	{"CSV Export Header", "track_csv_export_headers", "Boolean", ""},
	{"KML Export Timestamps", "track_kml_export_timestamps", "Boolean", ""},
	{"Server track time gap (minutes)", "bread_track_timegap_threshold", "String", "Numeric"},
	{"Persistent Self Track", "track_infinite", "Boolean", ""},
	{"Set Max Number of Bread Crumbs", "max_num_bread_tracks", "Integer", "0-500"},
	{"Render bread crumb line to ground in 3-D", "track_line_to_surface", "Boolean", ""},
	{"Default Crumb Size", "track_crumb_size", "String", "10; 15; 20"},
	{"Bread Crumb Distance Threshold", "bread_dist_threshold", "String", "Numeric"},
	{"Coordinate Display", "coord_display_pref", "String", "MGRS; DD; DM; DMS; UTM"},
	{"Altitude Display", "alt_display_pref", "String", "HAE; MSL"},
	{"Altitude Units", "alt_unit_pref", "String", "0 = Feet (ft); 1 = Meters (m)"},
	{"Display AGL", "alt_display_agl", "Boolean", ""},
	{"Speed Units", "speed_unit_pref", "String", "0 = Miles per hour (mph); 1 = KM per hour (kmph); 2 = KGS (kts); 3 = Meters Per Second (mps)"},
	{"Range and Bearing Line Distance Format", "rab_dist_slant_range", "String", "slantrange; clamped"},
	{"Bearing Units", "rab_brg_units_pref", "String", "0 = Degrees; 1 = Mils"},
	{"Range Units", "rab_rng_units_pref", "String", "0 = Feet/Miles; 1 = Meters/Kilometers; 2 = Nautical Miles"},
	{"North Reference", "rab_north_ref_pref", "String", "0 = True North; 1 = Magnetic North; 2 = Grid North"},
	{"Feet to Miles", "rng_feet_display_pref", "String", "Numeric"},
	{"Meters to Kilometers", "rng_meters_display_pref", "String", "Numeric"},
	{"Default Range and Bearing Color", "rab_color_pref", "String", ""},
	{"Display ETA on Range and Bearing Labels", "rab_preference_show_eta", "Boolean", ""},
	{"Set Domain Preference", "set_domain_pref", "String", "Ground; Aviation; Maritime"},
	{"Enable Zoom Controls", "map_zoom_visible", "Boolean", ""},
	{"Enable Map Scale Display", "map_scale_visible", "Boolean", ""},
	{"Enable Map Scale Rounding", "map_scale_rounding", "Boolean", ""},
	{"Designate the Map Center", "map_center_designator", "Boolean", ""},
	{"Self Coordinate Information", "self_coord_info_display", "String", "bottom_right; bottom_bar; none"},
	{"SidePane Handle Shade", "sidepane_handle_shade", "String", "Light; Dark"},
	{"Enable Large Text Mode", "largeTextMode", "Boolean", ""},
	{"Enable Large Tool Bar", "largeActionBar", "Boolean", ""},
	{"Icon and Text Size", "relativeOverlaysScalingRadioList", "String", "1.00 = Normal; 1.25 = 1.25x; 1.50 = 1.5x; 1.75 = 1.75x; 2.00 = 2x"},
	{"Default Label Size", "label_text_size", "String", "14 = Normal; 16 = Large; 18 = X-Large"},
	{"Map Overlay's Dimming/Brightening", "dim_map_with_brightness_key", "Boolean", ""},
	{"Adjust for Curved Display", "atakAdjustCurvedDisplay", "Boolean", ""},
	{"Enable the Faux Navigation Bar", "faux_nav_bar", "Boolean", ""},
	{"Reverse the buttons on the Faux Navigation Bar", "faux_nav_bar_reverse", "Boolean", ""},
	{"Disable AutoLink launching for Associated Links", "disable_autolink_mapitem_links", "Boolean", ""},
	{"Enable DEX Controls", "dexControls", "Boolean", ""},
	{"Enable Globe Display Mode", "atakGlobeModeEnabled", "Boolean", ""},
	{"Marker Size", "location_marker_scale_key", "String", "-1 = Default; 40 = 1x; 48 = 2x; 56 = 3x; 64 = 4x"},
	{"Default", "default_gps_icon", "Boolean", ""},
	{"Team Color", "team_color_gps_icon", "Boolean", ""},
	{"Custom", "custom_color_gps_icon_pref", "Boolean", ""},
	{"Change/Create Icon Main Custom Color", "custom_color_selected", "String", "16-bit Hexadecimal Color"},
	{"Change/Create Icon Outline Custom Color", "custom_outline_color_selected", "String", "16-bit Hexadecimal Color"},
	{"Toolbar Side", "nav_orientation_right", "Boolean", ""},
	{"Toolbar Icon Color", "actionbar_icon_color_key", "String", "16-bit Hexadecimal Color"},
	{"Toolbar Background Color", "actionbar_background_color_key", "String", "16-bit Hexadecimal Color"},
	{"Grid Line Color", "pref_grid_color", "String", "#ffffff = White; #ff00ff = Magenta; #00ff00 = Green; #ffff00 = Yellow; Custom"},
	{"Grid Line Color", "pref_grid_color_value", "String", "#ffffff = White; #ff00ff = Magenta; #00ff00 = Green; #ffff00 = Yellow; Any other HEX RGB value = Custom"},
	{"Show by Default", "prefs_grid_default_show", "Boolean", ""},
	{"Grid Line Display Type", "", "", ""},
	{"Layer Outline Color", "pref_layer_outline_color", "String", "#ffffff = White; #ff00ff = Magenta; #00ff00 = Green; #ffff00 = Yellow"},
	{"Show by Default", "prefs_layer_outlines_default_show", "Boolean", ""},
	{"Enabled on Start", "toggle_offscreen_indicators", "Boolean", ""},
	{"Set Distance Threshold (KM)", "offscreen_indicator_dist_threshold", "String", "Numeric"},
	{"Set Timeout Threshold (seconds) or zero to disable", "offscreen_indicator_timeout_threshold", "String", "Numeric"},
	{"Imported Shape Outline Color", "pref_overlay_style_outline_color", "String", "-1 through -16777216"},
	{"Overlay Manager Width/Height", "overlay_manager_width_height", "String", "50; 33; 25"},
	{"Forced Application Brightness", "atakForcedBrightness", "String", "-1 = None; 0 = Lowest; 25 = 25 percent; 50 = 50 percent; 75 = 75 percent; 100 = Highest"},
	{"Disable Screen Saver / Screen Lock", "atakScreenLock", "Boolean", ""},
	{"Disable SoftKey Illumination", "atakDisableSoftkeyIllumination", "Boolean", ""},
	{"Reverse Landscape Orientation", "atakControlReverseOrientation", "Boolean", ""},
	{"Shorten Long Marker Labels", "atakControlShortenLabels", "Boolean", ""},
	{"Show Marker Labels", "atakControlShowLabels", "Boolean", ""},
	{"Display Notifications for other users", "atakControlOtherUserNotification", "Boolean", ""},
	{"Fade Notification Time", "fade_notification", "String", "30 = 30 seconds; 60 = 60 seconds; 90 = 90 seconds; 120 = 2 minutes; 300 = 5 minutes; 600 = 10 minutes; 3600 = 1 hour; -1 = Do Not Fade"},
	{"Imagery Tab Name", "imagery_tab_name", "String", "Imagery; Maps"},
	{"Render Speed", "frame_limit", "String", "0 = Full speed; 1 = Battery saver"},
	{"Secure Delete Timeout", "secureDeleteTimeout", "String", "Numeric"},
	{"Prefer KLV Frame Center Elevation", "prefs_use_klv_elevation", "Boolean", ""},
	{"Camera Application", "quickpic.camera_chooser", "String", "System; TakGeoCam"},
	{"Force Center while Moving", "disableFloatToBottom", "Boolean", ""},
	{"Stale out remote users as they disconnect from TAK Servers", "staleRemoteDisconnects", "Boolean", ""},
	{"Remove all marker types from map when they stale out", "expireEverything", "Boolean", ""},
	{"Stale item cleanup time", "expireStaleItemsTime", "String", "0 = Immediately; 1 = 1 minute; 5 = 5 minutes; 20 = 20 minutes; 60 = 1 hour; 360 = 6 hours;1440 = 1 day"},
	{"Remove Unknown markers when they stale out", "expireUnknowns", "Boolean", ""},
	{"Quit on Back Press", "atakControlQuitOnBack", "Boolean", ""},
	{"Ask Before Quit", "atakControlAskToQuit", "Boolean", ""},
	{"Action for Long Pressing the Map", "atakLongPressMap", "String", "nothing = Do Nothing; actionbar = Toggle the Toolbar; dropicon = Drop a Point"},
	{"Double tap to zoom 2X", "atakDoubleTapToZoom", "Boolean", ""},
	{"Self Coordinate Information", "self_coord_info_display", "String", ""},
	{"Tap Coordinate Action", "self_coord_action", "String", "nothing = Do Nothing; cyclecoordinate = Change Coordinates; panto = Pan to Self"},
	{"Enable enlarging the coordinate display", "selfcoord_legacy_enlarge", "Boolean", ""},
	{"Legacy Point Drop Naming Convention", "legacyPointDropNaming", "Boolean", ""},
	{"Disable KeyGuard", "disableLeyGuard", "Boolean", ""},
	{"Forced Airplane Mode", "atakForceAirplaneRadioList", "String", "none = Do not Force; cell = Force General Radio Off; cell, wifi = Force General Radio and Wireless Off"},
	{"Continuous Rendering", "atakContinuousRender", "Boolean", ""},
	{"Developer Tools", "atakDeveloperTools", "Boolean", ""},
	{"Auto Upload App Logs", "enableAutoUploadLogs", "Boolean", ""},
	{"Collect Metrics", "collect_metrics", "Boolean", ""},
	{"Live Metrics", "realtime_metrics", "Boolean", ""},
	{"Enable Logcat File", "loggingfile", "Boolean", ""},
	{"Enable Logcat Errors Only", "loggingfile_error_only", "Boolean", ""},
	{"Upload Debug Logs", "loggingfile_upload_debug", "Boolean", ""},
	{"Collect Metrics", "collect_metrics", "Boolean", ""},
	{"Log Network Traffic", "lognettraffictofile", "Boolean", ""},
	{"Advanced CoT Recorder", "generate_full_pool", "Boolean", ""},
	{"Advanced CoT Details Recorder", "generate_detail_pool", "Boolean", ""},
	{"Disable EUD Link", "eud_api_disable_option", "Boolean", ""},
	{"Scroll to Self Marker Location on Start", "scrollToSelfOnStart", "Boolean", ""},

	{"Hide 9-line/5-line Control Preferences", "hidePreferenceItem_nineLineControlPreference", "Boolean", ""},
	{"Hide About", "hidePreferenceItem_about", "Boolean", ""},
	{"Hide Accounts", "hidePreferenceItem_atakAccounts", "Boolean", ""},
	{"Hide Addendum", "hidePreferenceItem_atakFlavorAddendum", "Boolean", ""},
	{"Hide Address Lookup Preferences", "hidePreferenceItem_geocoderPreferences", "Boolean", ""},
	{"Hide Address Provider", "hidePreferenceItem_geocodeSupplier", "Boolean", ""},
	{"Hide Adjust for Curved Display", "hidePreferenceItem_atakAdjustCurvedDisplay", "Boolean", ""},
	{"Hide Alert Preferences", "hidePreferenceItem_alertPreference", "Boolean", ""},
	{"Hide Alert SMS Numbers", "hidePreferenceItem_sms_numbers", "Boolean", ""},
	{"Hide Android Display Preferences", "hidePreferenceItem_displaySettings", "Boolean", ""},
	{"Hide Apply TAK Server profile updates", "hidePreferenceItem_deviceProfileEnableOnConnect", "Boolean", ""},
	{"Hide ATAK Dataset Instructions", "hidePreferenceItem_atakDatasets", "Boolean", ""},
	{"Hide ATAK Release Change Log", "hidePreferenceItem_atakChangeLog", "Boolean", ""},
	{"Hide ATAK User Manual", "hidePreferenceItem_atakDocumentation", "Boolean", ""},
	{"Hide Audible alert", "hidePreferenceItem_alert_audible", "Boolean", ""},
	{"Hide Audible Chat notifications", "hidePreferenceItem_audibleNotify", "Boolean", ""},
	{"Hide Auto Manage Mesh Network Self SA Mode", "hidePreferenceItem_autoDisableMeshSAWhenStreaming", "Boolean", ""},
	{"Hide Automatically Broadcast a Marker", "hidePreferenceItem_hostileUpdateDelay", "Boolean", ""},
	{"Hide Auto Rotate Track Colors", "hidePreferenceItem_toggle_rotate_track_colors", "Boolean", ""},
	{"Hide Billboard Render Distance", "hidePreferenceItem_route_billboard_distance_m", "Boolean", ""},
	{"Hide Bloodhound Preferences", "hidePreferenceItem_bloodhoundPreferences", "Boolean", ""},
	{"Hide Bluetooth Preferences", "hidePreferenceItem_bluetoothPref", "Boolean", ""},
	{"Hide Bluetooth Reconnect Time", "hidePreferenceItem_atakBluetoothReconnectSeconds", "Boolean", ""},
	{"Hide Bluetooth Support", "hidePreferenceItem_atakControlBluetooth", "Boolean", ""},
	{"Hide Bread Crumb Distance Threshold", "hidePreferenceItem_bread_dist_threshold", "Boolean", ""},
	{"Hide Certificate Enrollment API port", "hidePreferenceItem_apiCertEnrollmentPort", "Boolean", ""},
	{"Hide Certificate Enrollment Key Length", "hidePreferenceItem_apiCertEnrollmentKeyLength", "Boolean", ""},
	{"Hide Change/Create Custom Color", "hidePreferenceItem_change_custom_gps_color", "Boolean", ""},
	{"Hide Change Encryption Passphrase", "hidePreferenceItem_encryptionPassphrase", "Boolean", ""},
	{"Hide Chat Address", "hidePreferenceItem_chatAddress", "Boolean", ""},
	{"Hide Chat Port", "hidePreferenceItem_chatPort", "Boolean", ""},
	{"Hide Chat Preferences", "hidePreferenceItem_chatPreference", "Boolean", ""},
	{"Hide Checkpoint Name Prefix", "hidePreferenceItem_waypointPrefix", "Boolean", ""},
	{"Hide Clear Attachments", "hidePreferenceItem_clearMedia", "Boolean", ""},
	{"Hide Clear History", "hidePreferenceItem_clearHistory", "Boolean", ""},
	{"Hide Configure AES-256 Mesh Encryption", "hidePreferenceItem_configureNonStreamingEncryption", "Boolean", ""},
	{"Hide Constant Reporting Rate (Reliable)", "hidePreferenceItem_constantReportingRateReliable", "Boolean", ""},
	{"Hide Constant Reporting Rate (Unreliable)", "hidePreferenceItem_constantReportingRateUnreliable", "Boolean", ""},
	{"Hide Contact Preferences", "hidePreferenceItem_alternateContactCategory", "Boolean", ""},
	{"Hide Control Preferences", "hidePreferenceItem_atakControlOptions", "Boolean", ""},
	{"Hide CSV Export Header", "hidePreferenceItem_track_csv_export_headers", "Boolean", ""},
	{"Hide Custom", "hidePreferenceItem_custom_color_gps_icon_pref", "Boolean", ""},
	{"Hide Default Color", "hidePreferenceItem_track_history_default_color", "Boolean", ""},
	{"Hide Default Crumb Size", "hidePreferenceItem_track_crumb_size", "Boolean", ""},
	{"Hide Default for unspecified Route Colors", "hidePreferenceItem_defaultRouteColor", "Boolean", ""},
	{"Hide Default gateway", "hidePreferenceItem_network_static_gateway", "Boolean", ""},
	{"Hide Default", "hidePreferenceItem_default_gps_icon", "Boolean", ""},
	{"Hide Default Label Size", "hidePreferenceItem_label_text_size", "Boolean", ""},
	{"Hide Default SSL/TLS Client Certificate Password", "hidePreferenceItem_clientPassword", "Boolean", ""},
	{"Hide Default SSL/TLS Client Certificate Store", "hidePreferenceItem_certificateLocation", "Boolean", ""},
	{"Hide Default SSL/TLS Credentials", "hidePreferenceItem_default_client_credentials", "Boolean", ""},
	{"Hide Default SSL/TLS TrustStore Location", "hidePreferenceItem_caLocation", "Boolean", ""},
	{"Hide Default SSL/TLS TrustStore Password", "hidePreferenceItem_caPassword", "Boolean", ""},
	{"Hide Designate the Map Center", "hidePreferenceItem_map_center_designator", "Boolean", ""},
	{"Hide Device Preferences", "hidePreferenceItem_deviceSettings", "Boolean", ""},
	{"Hide DHCP", "hidePreferenceItem_network_dhcp", "Boolean", ""},
	{"Hide Digital Pointer Preferences", "hidePreferenceItem_fire_prefs_category", "Boolean", ""},
	{"Hide Disable Screen Saver / Screen Lock", "hidePreferenceItem_atakScreenLock", "Boolean", ""},
	{"Hide Disable SoftKey Illumination", "hidePreferenceItem_atakDisableSoftkeyIllumination", "Boolean", ""},
	{"Hide Display Bloodhound Text Widget", "hidePreferenceItem_rab_bloodhound_display_textwidget", "Boolean", ""},
	{"Hide Display Connection Widget", "hidePreferenceItem_displayServerConnectionWidget", "Boolean", ""},
	{"Hide Display Large Bloodhound Text Widget", "hidePreferenceItem_rab_bloodhound_large_textwidget", "Boolean", ""},
	{"Hide Display °M Unit in Doghouse", "hidePreferenceItem_doghouseShowNorthReference", "Boolean", ""},
	{"Hide Display Notification", "hidePreferenceItem_enableToast", "Boolean", ""},
	{"Hide Display Notifications for other users", "hidePreferenceItem_atakControlOtherUserNotification", "Boolean", ""},
	{"Hide Display Preferences", "hidePreferenceItem_generalDisplayPref", "Boolean", ""},
	{"Hide Display the Self Coordinate Information", "hidePreferenceItem_show_self_coordinate_overlay", "Boolean", ""},
	{"Hide DNS 1", "hidePreferenceItem_network_static_dns1", "Boolean", ""},
	{"Hide DNS 2", "hidePreferenceItem_network_static_dns2", "Boolean", ""},
	{"Hide Download attempts", "hidePreferenceItem_fileshareDownloadAttempts", "Boolean", ""},
	{"Hide DP/RedX FAH Width", "hidePreferenceItem_spiFahSize", "Boolean", ""},
	{"Hide DP Update Period", "hidePreferenceItem_spiUpdateDelay", "Boolean", ""},
	{"Hide Driving Checkpoint Navigation Bubble Radius", "hidePreferenceItem_waypointBubble.Driving", "Boolean", ""},
	{"Hide Driving Off Route Bubble Radius", "hidePreferenceItem_waypointOffRouteBubble.Driving", "Boolean", ""},
	{"Hide Dynamic Reporting Rate Maximum (Reliable)", "hidePreferenceItem_dynamicReportingRateMaxReliable", "Boolean", ""},
	{"Hide Dynamic Reporting Rate Maximum (Unreliable)", "hidePreferenceItem_dynamicReportingRateMaxUnreliable", "Boolean", ""},
	{"Hide Dynamic Reporting Rate Minimum (Reliable)", "hidePreferenceItem_dynamicReportingRateMinReliable", "Boolean", ""},
	{"Hide Dynamic Reporting Rate Minimum (Unreliable)", "hidePreferenceItem_dynamicReportingRateMinUnreliable", "Boolean", ""},
	{"Hide Dynamic Reporting Rate Stationary (Reliable)", "hidePreferenceItem_dynamicReportingRateStationaryReliable", "Boolean", ""},
	{"Hide Dynamic Reporting Rate Stationary (Unreliable)", "hidePreferenceItem_dynamicReportingRateStationaryUnreliable", "Boolean", ""},
	{"Hide Elevation Overlays Preferences", "hidePreferenceItem_dtedPreference", "Boolean", ""},
	{"Hide Elevation Profile Center on Seeker", "hidePreferenceItem_elevProfileCenterOnSeeker", "Boolean", ""},
	{"Hide Elevation Profile Interpolate Altitudes", "hidePreferenceItem_elevProfileInterpolateAlt", "Boolean", ""},
	{"Hide Enable Address Lookup (Geocoder)", "hidePreferenceItem_enableGeocoder", "Boolean", ""},
	{"Hide Enable Client Certificate Export", "hidePreferenceItem_certEnrollmentExport", "Boolean", ""},
	{"Hide Enable DEX Friendly Controls", "hidePreferenceItem_dexControls", "Boolean", ""},
	{"Hide Enable Globe Display Mode", "hidePreferenceItem_atakGlobeModeEnabled", "Boolean", ""},
	{"Hide Enable Image Overlay Map Interaction", "hidePreferenceItem_prefs_layer_grg_map_interaction", "Boolean", ""},
	{"Hide Enable Large Text Mode", "hidePreferenceItem_largeTextMode", "Boolean", ""},
	{"Hide Enable Large Tool Bar", "hidePreferenceItem_largeActionBar", "Boolean", ""},
	{"Hide Enable Map Scale Display", "hidePreferenceItem_map_scale_visible", "Boolean", ""},
	{"Hide Enable Map Scale Rounding", "hidePreferenceItem_map_scale_rounding", "Boolean", ""},
	{"Hide Enable Mesh Network Mode", "hidePreferenceItem_enableNonStreamingConnections", "Boolean", ""},
	{"Hide Enable the Faux Navigation Bar", "hidePreferenceItem_faux_nav_bar", "Boolean", ""},
	{"Hide Enable Volume Keys rotating map layers", "hidePreferenceItem_volumemapswitcher", "Boolean", ""},
	{"Hide Expanded Danger Close Search", "hidePreferenceItem_expandedDangerClose", "Boolean", ""},
	{"Hide Export Chat History", "hidePreferenceItem_exportHistory", "Boolean", ""},
	{"Hide Fade Notification Time", "hidePreferenceItem_fade_notification", "Boolean", ""},
	{"Hide FAH Distance (NM)", "hidePreferenceItem_fahDistance", "Boolean", ""},
	{"Hide File Transfer Connection Timeout", "hidePreferenceItem_filesharingConnectionTimeoutSecs", "Boolean", ""},
	{"Hide File Transfer Failure Timeout", "hidePreferenceItem_filesharingTransferTimeoutSecs", "Boolean", ""},
	{"Hide File Transfer Max size", "hidePreferenceItem_filesharingSizeThresholdNoGo", "Boolean", ""},
	{"Hide Fires Toolbar Preferences", "hidePreferenceItem_firesPreference", "Boolean", ""},
	{"Hide Flash Color", "hidePreferenceItem_bloodhound_flash_color_pref", "Boolean", ""},
	{"Hide Flash ETA Threshold", "hidePreferenceItem_bloodhound_flash_eta", "Boolean", ""},
	{"Hide Flash When Closing In", "hidePreferenceItem_rab_bloodhound_flash_colors", "Boolean", ""},
	{"Hide Flying Checkpoint Navigation Bubble Radius", "hidePreferenceItem_waypointBubble.Flying", "Boolean", ""},
	{"Hide Flying Off Route Bubble Radius", "hidePreferenceItem_waypointOffRouteBubble.Flying", "Boolean", ""},
	{"Hide Forced Application Brightness", "hidePreferenceItem_atakForcedBrightness", "Boolean", ""},
	{"Hide Force Reset Layer Cache", "hidePreferenceItem_mediaLayerCacheForceRescan", "Boolean", ""},
	{"Hide GPS Option", "hidePreferenceItem_mockingOption", "Boolean", ""},
	{"Hide GPS Preferences", "hidePreferenceItem_gpsSettings", "Boolean", ""},
	{"Hide GPS Preferences", "hidePreferenceItem_networkGpsCategory", "Boolean", ""},
	{"Hide GPX Import Checkpoints", "hidePreferenceItem_gpxImportCheckpointsForNamedRoutePoints", "Boolean", ""},
	{"Hide Grid Line Preferences", "hidePreferenceItem_gridLinesPreference", "Boolean", ""},
	{"Hide Hide my current position", "hidePreferenceItem_dispatchLocationHidden", "Boolean", ""},
	{"Hide Icon and Text Size", "hidePreferenceItem_relativeOverlaysScalingRadioList", "Boolean", ""},
	{"Hide Idle Stream", "hidePreferenceItem_video_dropdown_hidden_disconnect", "Boolean", ""},
	{"Hide Ignore Elevation Data", "hidePreferenceItem_kmlExportGroundClamp", "Boolean", ""},
	{"Hide Imagery Layer Outline Preferences", "hidePreferenceItem_layerOutlinesPreference", "Boolean", ""},
	{"Hide Imagery Tab Name", "hidePreferenceItem_imagery_tab_name", "Boolean", ""},
	{"Hide Import Style Default Preferences", "hidePreferenceItem_overlayStylePreference", "Boolean", ""},
	{"Hide Individual Alert Notifications", "hidePreferenceItem_individual_alert_notification", "Boolean", ""},
	{"Hide Inner ETA Color", "hidePreferenceItem_bloodhound_inner_color_pref", "Boolean", ""},
	{"Hide Internal Network Configuration", "hidePreferenceItem_network_config", "Boolean", ""},
	{"Hide IP address", "hidePreferenceItem_network_static_ip_address", "Boolean", ""},
	{"Hide KML Export Checkpoint Mode", "hidePreferenceItem_kmlExportCheckpointMode", "Boolean", ""},
	{"Hide KML Export Timestamps", "hidePreferenceItem_track_kml_export_timestamps", "Boolean", ""},
	{"Hide Laser Basket Distance (NM)", "hidePreferenceItem_laserBasketDistance", "Boolean", ""},
	{"Hide Legacy Settings View", "hidePreferenceItem_legacy_settings", "Boolean", ""},
	{"Hide Legacy Toolbar Mode", "hidePreferenceItem_legacyFiresToolbarMode", "Boolean", ""},
	{"Hide Legacy Wave Relay Redirect", "hidePreferenceItem_waveRelayRedirect", "Boolean", ""},
	{"Hide Load Preference Category", "hidePreferenceItem_loadPartialPrefs", "Boolean", ""},
	{"Hide Load Preferences", "hidePreferenceItem_loadPrefs", "Boolean", ""},
	{"Hide Logging Preferences", "hidePreferenceItem_settingsLogging", "Boolean", ""},
	{"Hide Log Tracks", "hidePreferenceItem_toggle_log_tracks", "Boolean", ""},
	{"Hide Manage Inputs", "hidePreferenceItem_manageInputsLink", "Boolean", ""},
	{"Hide Manage Outputs", "hidePreferenceItem_manageOutputsLink", "Boolean", ""},
	{"Hide Manage Persisted IDs", "hidePreferenceItem_tadiljPersistedIds", "Boolean", ""},
	{"Hide Manage Server Connections", "hidePreferenceItem_manageStreamingLink", "Boolean", ""},
	{"Hide Map Data Preferences", "hidePreferenceItem_wmsPreferences", "Boolean", ""},
	{"Hide Map Overlays Dimming/Brightening", "hidePreferenceItem_dim_map_with_brightness_key", "Boolean", ""},
	{"Hide Media Preferences", "hidePreferenceItem_mediaPreference", "Boolean", ""},
	{"Hide Metric Report Preferences", "hidePreferenceItem_metricsPreference", "Boolean", ""},
	{"Hide Middle ETA Color", "hidePreferenceItem_bloodhound_middle_color_pref", "Boolean", ""},
	{"Hide Middle/Inner ETA Threshold", "hidePreferenceItem_bloodhound_inner_eta", "Boolean", ""},
	{"Hide Mission Package Control Preferences", "hidePreferenceItem_missionpackagePreference", "Boolean", ""},
	{"Hide Monitor Server Connections", "hidePreferenceItem_monitorServerConnections", "Boolean", ""},
	{"Hide MulticastRejoin interval", "hidePreferenceItem_udpNoDataTimeout", "Boolean", ""},
	{"Hide Multicast Traffic Loopback", "hidePreferenceItem_network_multicast_loopback", "Boolean", ""},
	{"Hide Multicast TTL", "hidePreferenceItem_multicastTTL", "Boolean", ""},
	{"Hide My Callsign", "hidePreferenceItem_locationCallsign", "Boolean", ""},
	{"Hide My Callsign", "hidePreferenceItem_myIdentity", "Boolean", ""},
	{"Hide My Display Type", "hidePreferenceItem_locationUnitType", "Boolean", ""},
	{"Hide My Location Color / Size", "hidePreferenceItem_my_location_icon_color", "Boolean", ""},
	{"Hide My Preferences", "hidePreferenceItem_mySettings", "Boolean", ""},
	{"Hide My Role", "hidePreferenceItem_atakRoleType", "Boolean", ""},
	{"Hide My Team", "hidePreferenceItem_locationTeam", "Boolean", ""},
	{"Hide Navigational Voice Cues", "hidePreferenceItem_useRouteVoiceCues", "Boolean", ""},
	{"Hide Network Connection Preferences", "hidePreferenceItem_networkSettings", "Boolean", ""},
	{"Hide Network GPS", "hidePreferenceItem_gpsSettings", "Boolean", ""},
	{"Hide Network GPS", "hidePreferenceItem_networkCategory", "Boolean", ""},
	{"Hide Network GPS Option", "hidePreferenceItem_mockingOption", "Boolean", ""},
	{"Hide Network GPS Port", "hidePreferenceItem_listenPort", "Boolean", ""},
	{"Hide Network Preferences", "hidePreferenceItem_settingsPref", "Boolean", ""},
	{"Hide NGA Memorandum for Record (PFI)", "hidePreferenceItem_ngaCertification", "Boolean", ""},
	{"Hide Notification", "hidePreferenceItem_alert_notification", "Boolean", ""},
	{"Hide Number of DPs", "hidePreferenceItem_firesNumberOfSpis", "Boolean", ""},
	{"Hide Off-Screen Indicators Preferences", "hidePreferenceItem_atakOffScrIndiOptions", "Boolean", ""},
	{"Hide Outer ETA Color", "hidePreferenceItem_bloodhound_outer_color_pref", "Boolean", ""},
	{"Hide Outer/Middle ETA Threshold", "hidePreferenceItem_bloodhound_outer_eta", "Boolean", ""},
	{"Hide Overlay Manager Width/Height", "hidePreferenceItem_overlay_manager_width_height", "Boolean", ""},
	{"Hide Persistent Self Track", "hidePreferenceItem_track_infinite", "Boolean", ""},
	{"Hide Point-to-Point Link High Speed Capable", "hidePreferenceItem_ppp0_highspeed_capable", "Boolean", ""},
	{"Hide Prepare for Cloning / Clear Device unique information", "hidePreferenceItem_prepareForClone", "Boolean", ""},
	{"Hide Publish phone number", "hidePreferenceItem_saHasPhoneNumber", "Boolean", ""},
	{"Hide Publish Preferred Email", "hidePreferenceItem_saEmailAddress", "Boolean", ""},
	{"Hide Publish VoIP Number", "hidePreferenceItem_saSipAddressAssignment", "Boolean", ""},
	{"Hide Publish XMPP Username", "hidePreferenceItem_saXmppUsername", "Boolean", ""},
	{"Hide Redeploy WMS Sources", "hidePreferenceItem_redeploywms", "Boolean", ""},
	{"Hide Render bread crumb line to ground in 3-D", "hidePreferenceItem_track_line_to_surface", "Boolean", ""},
	{"Hide Render Speed", "hidePreferenceItem_frame_limit", "Boolean", ""},
	{"Hide Reporting Preferences", "hidePreferenceItem_publishCategory", "Boolean", ""},
	{"Hide Reporting Preferences", "hidePreferenceItem_reportingSettings", "Boolean", ""},
	{"Hide Reporting Strategy", "hidePreferenceItem_locationReportingStrategy", "Boolean", ""},
	{"Hide Report Location before obtaining location fix", "hidePreferenceItem_dispatchLocationCotExternalAtStart", "Boolean", ""},
	{"Hide Request Delay", "hidePreferenceItem_requestDelay", "Boolean", ""},
	{"Hide Reroute distance", "hidePreferenceItem_bloodhound_reroute_distance_pref", "Boolean", ""},
	{"Hide Reroute timer frequency", "hidePreferenceItem_bloodhound_reroute_timer_pref", "Boolean", ""},
	{"Hide Reset Hints", "hidePreferenceItem_resetHints", "Boolean", ""},
	{"Hide Reset Tool Bar Colors To Default", "hidePreferenceItem_default_actionbar_colors", "Boolean", ""},
	{"Hide Reverse Landscape Orientation", "hidePreferenceItem_atakControlReverseOrientation", "Boolean", ""},
	{"Hide Reverse the buttons on the Faux Navigation Bar", "hidePreferenceItem_faux_nav_bar_reverse", "Boolean", ""},
	{"Hide Route Preferences", "hidePreferenceItem_routePreference", "Boolean", ""},
	{"Hide Rover Control Preferences", "hidePreferenceItem_isrvNetworkPreference", "Boolean", ""},
	{"Hide Save Preferences", "hidePreferenceItem_savePrefs", "Boolean", ""},
	{"Hide Secure Server API port", "hidePreferenceItem_apiSecureServerPort", "Boolean", ""},
	{"Hide Send Location Over Network", "hidePreferenceItem_dispatchLocationCotExternal", "Boolean", ""},
	{"Hide Server port", "hidePreferenceItem_filesharingWebServerPort", "Boolean", ""},
	{"Hide Server track time gap (minutes)", "hidePreferenceItem_bread_track_timegap_threshold", "Boolean", ""},
	{"Hide Set Distance Threshold (KM)", "hidePreferenceItem_offscreen_indicator_dist_threshold", "Boolean", ""},
	{"Hide Set Max Number of Bread Crumbs", "hidePreferenceItem_max_num_bread_tracks", "Boolean", ""},
	{"Hide Set Timeout Threshold (seconds) or zero to disable", "hidePreferenceItem_offscreen_indicator_timeout_threshold", "Boolean", ""},
	{"Hide Shorten Long Marker Labels", "hidePreferenceItem_atakControlShortenLabels", "Boolean", ""},
	{"Hide Show All Preferences", "hidePreferenceItem_atakControlOptions", "Boolean", ""},
	{"Hide Show Attachment Billboards", "hidePreferenceItem_route_billboard_enabled", "Boolean", ""},
	{"Hide Show by Default", "hidePreferenceItem_prefs_dted_visible", "Boolean", ""},
	{"Hide Show Marker Labels", "hidePreferenceItem_atakControlShowLabels", "Boolean", ""},
	{"Hide Subnet mask", "hidePreferenceItem_network_static_subnet_mask", "Boolean", ""},
	{"Hide Support", "hidePreferenceItem_documentation", "Boolean", ""},
	{"Hide Swimming Checkpoint Navigation Bubble Radius", "hidePreferenceItem_waypointBubble.Swimming", "Boolean", ""},
	{"Hide Swimming Off Route Bubble Radius", "hidePreferenceItem_waypointOffRouteBubble.Swimming", "Boolean", ""},
	{"Hide TADIL-J Preferences", "hidePreferenceItem_tadiljSettings", "Boolean", ""},
	{"Hide TAK Device Configuration", "hidePreferenceItem_resetDeviceConfig", "Boolean", ""},
	{"Hide TAK Package Mgmt", "hidePreferenceItem_appsPref", "Boolean", ""},
	{"Hide TAK Package Mgmt", "hidePreferenceItem_myPlugins", "Boolean", ""},
	{"Hide TAK Servers", "hidePreferenceItem_myServers", "Boolean", ""},
	{"Hide TAK Support Information", "hidePreferenceItem_atakSupport", "Boolean", ""},
	{"Hide TCP Connection Timeout", "hidePreferenceItem_tcpConnectTimeout", "Boolean", ""},
	{"Hide Team Color", "hidePreferenceItem_team_color_gps_icon", "Boolean", ""},
	{"Hide Test Address Provider", "hidePreferenceItem_geocodeTestConnection", "Boolean", ""},
	{"Hide Toggle Auto Zoom", "hidePreferenceItem_rab_bloodhound_zoom", "Boolean", ""},
	{"Hide Tool Bar Background Color", "hidePreferenceItem_selected_actionbar_background_color", "Boolean", ""},
	{"Hide Tool Bar Customization", "hidePreferenceItem_my_actionbar_settings", "Boolean", ""},
	{"Hide Tool Bar Icon Color", "hidePreferenceItem_custom_actionbar_icon_color", "Boolean", ""},
	{"Hide Tool Preferences", "hidePreferenceItem_toolsPref", "Boolean", ""},
	{"Hide Track History Preferences", "hidePreferenceItem_atakTrackOptions", "Boolean", ""},
	{"Hide Track Prefix", "hidePreferenceItem_track_prefix", "Boolean", ""},
	{"Hide Traditional Navigation Mode", "hidePreferenceItem_route_track_up_locked_on", "Boolean", ""},
	{"Hide Unit Display Format Preferences", "hidePreferenceItem_unitPreferences", "Boolean", ""},
	{"Hide Unsecure Server API port", "hidePreferenceItem_apiUnsecureServerPort", "Boolean", ""},
	{"Hide Use Android Geocoder", "hidePreferenceItem_builtInGeocoder", "Boolean", ""},
	{"Hide Use GPS Time", "hidePreferenceItem_useGPSTime", "Boolean", ""},
	{"Hide Use Wave Relay Callsign", "hidePreferenceItem_locationUseWRCallsign", "Boolean", ""},
	{"Hide Vibrate phone", "hidePreferenceItem_vibratePhone", "Boolean", ""},
	{"Hide Vibrate When Arriving at Checkpoint", "hidePreferenceItem_route_vibrate_at_checkpoint", "Boolean", ""},
	{"Hide Vibration alert", "hidePreferenceItem_alert_vibration", "Boolean", ""},
	{"Hide Video Preferences", "hidePreferenceItem_videoPreference", "Boolean", ""},
	{"Hide VoIP Number", "hidePreferenceItem_saSipAddress", "Boolean", ""},
	{"Hide Walking Checkpoint Navigation Bubble Radius", "hidePreferenceItem_waypointBubble.Walking", "Boolean", ""},
	{"Hide Walking Off Route Bubble Radius", "hidePreferenceItem_waypointOffRouteBubble.Walking", "Boolean", ""},
	{"Hide Watercraft Checkpoint Navigation Bubble Radius", "hidePreferenceItem_waypointBubble.Watercraft", "Boolean", ""},
	{"Hide Watercraft Off Route Bubble Radius", "hidePreferenceItem_waypointOffRouteBubble.Watercraft", "Boolean", ""},
	{"Hide WMS Connect Timeout", "hidePreferenceItem_wmsconnecttimeout", "Boolean", ""}, {"Hide 9-line/5-line Control Preferences", "hidePreferenceItem_nineLineControlPreference", "Boolean", ""},

	{"Disable About", "disablePreferenceItem_about", "Boolean", ""},
	{"Disable Accounts", "disablePreferenceItem_atakAccounts", "Boolean", ""},
	{"Disable Addendum", "disablePreferenceItem_atakFlavorAddendum", "Boolean", ""},
	{"Disable Address Lookup Preferences", "disablePreferenceItem_geocoderPreferences", "Boolean", ""},
	{"Disable Address Provider", "disablePreferenceItem_geocodeSupplier", "Boolean", ""},
	{"Disable Adjust for Curved Display", "disablePreferenceItem_atakAdjustCurvedDisplay", "Boolean", ""},
	{"Disable Alert Preferences", "disablePreferenceItem_alertPreference", "Boolean", ""},
	{"Disable Alert SMS Numbers", "disablePreferenceItem_sms_numbers", "Boolean", ""},
	{"Disable Android Display Preferences", "disablePreferenceItem_displaySettings", "Boolean", ""},
	{"Disable Apply TAK Server profile updates", "disablePreferenceItem_deviceProfileEnableOnConnect", "Boolean", ""},
	{"Disable ATAK Dataset Instructions", "disablePreferenceItem_atakDatasets", "Boolean", ""},
	{"Disable ATAK Release Change Log", "disablePreferenceItem_atakChangeLog", "Boolean", ""},
	{"Disable ATAK User Manual", "disablePreferenceItem_atakDocumentation", "Boolean", ""},
	{"Disable Audible alert", "disablePreferenceItem_alert_audible", "Boolean", ""},
	{"Disable Audible Chat notifications", "disablePreferenceItem_audibleNotify", "Boolean", ""},
	{"Disable Auto Manage Mesh Network Self SA Mode", "disablePreferenceItem_autoDisableMeshSAWhenStreaming", "Boolean", ""},
	{"Disable Automatically Broadcast a Marker", "disablePreferenceItem_hostileUpdateDelay", "Boolean", ""},
	{"Disable Auto Rotate Track Colors", "disablePreferenceItem_toggle_rotate_track_colors", "Boolean", ""},
	{"Disable Billboard Render Distance", "disablePreferenceItem_route_billboard_distance_m", "Boolean", ""},
	{"Disable Bloodhound Preferences", "disablePreferenceItem_bloodhoundPreferences", "Boolean", ""},
	{"Disable Bluetooth Preferences", "disablePreferenceItem_bluetoothPref", "Boolean", ""},
	{"Disable Bluetooth Reconnect Time", "disablePreferenceItem_atakBluetoothReconnectSeconds", "Boolean", ""},
	{"Disable Bluetooth Support", "disablePreferenceItem_atakControlBluetooth", "Boolean", ""},
	{"Disable Bread Crumb Distance Threshold", "disablePreferenceItem_bread_dist_threshold", "Boolean", ""},
	{"Disable Certificate Enrollment API port", "disablePreferenceItem_apiCertEnrollmentPort", "Boolean", ""},
	{"Disable Certificate Enrollment Key Length", "disablePreferenceItem_apiCertEnrollmentKeyLength", "Boolean", ""},
	{"Disable Change/Create Custom Color", "disablePreferenceItem_change_custom_gps_color", "Boolean", ""},
	{"Disable Change Encryption Passphrase", "disablePreferenceItem_encryptionPassphrase", "Boolean", ""},
	{"Disable Chat Address", "disablePreferenceItem_chatAddress", "Boolean", ""},
	{"Disable Chat Port", "disablePreferenceItem_chatPort", "Boolean", ""},
	{"Disable Chat Preferences", "disablePreferenceItem_chatPreference", "Boolean", ""},
	{"Disable Checkpoint Name Prefix", "disablePreferenceItem_waypointPrefix", "Boolean", ""},
	{"Disable Clear Attachments", "disablePreferenceItem_clearMedia", "Boolean", ""},
	{"Disable Clear History", "disablePreferenceItem_clearHistory", "Boolean", ""},
	{"Disable Configure AES-256 Mesh Encryption", "disablePreferenceItem_configureNonStreamingEncryption", "Boolean", ""},
	{"Disable Constant Reporting Rate (Reliable)", "disablePreferenceItem_constantReportingRateReliable", "Boolean", ""},
	{"Disable Constant Reporting Rate (Unreliable)", "disablePreferenceItem_constantReportingRateUnreliable", "Boolean", ""},
	{"Disable Contact Preferences", "disablePreferenceItem_alternateContactCategory", "Boolean", ""},
	{"Disable Control Preferences", "disablePreferenceItem_atakControlOptions", "Boolean", ""},
	{"Disable CSV Export Header", "disablePreferenceItem_track_csv_export_headers", "Boolean", ""},
	{"Disable Custom", "disablePreferenceItem_custom_color_gps_icon_pref", "Boolean", ""},
	{"Disable Default Color", "disablePreferenceItem_track_history_default_color", "Boolean", ""},
	{"Disable Default Crumb Size", "disablePreferenceItem_track_crumb_size", "Boolean", ""},
	{"Disable Default for unspecified Route Colors", "disablePreferenceItem_defaultRouteColor", "Boolean", ""},
	{"Disable Default gateway", "disablePreferenceItem_network_static_gateway", "Boolean", ""},
	{"Disable Default", "disablePreferenceItem_default_gps_icon", "Boolean", ""},
	{"Disable Default Label Size", "disablePreferenceItem_label_text_size", "Boolean", ""},
	{"Disable Default SSL/TLS Client Certificate Password", "disablePreferenceItem_clientPassword", "Boolean", ""},
	{"Disable Default SSL/TLS Client Certificate Store", "disablePreferenceItem_certificateLocation", "Boolean", ""},
	{"Disable Default SSL/TLS Credentials", "disablePreferenceItem_default_client_credentials", "Boolean", ""},
	{"Disable Default SSL/TLS TrustStore Location", "disablePreferenceItem_caLocation", "Boolean", ""},
	{"Disable Default SSL/TLS TrustStore Password", "disablePreferenceItem_caPassword", "Boolean", ""},
	{"Disable Designate the Map Center", "disablePreferenceItem_map_center_designator", "Boolean", ""},
	{"Disable Device Preferences", "disablePreferenceItem_deviceSettings", "Boolean", ""},
	{"Disable DHCP", "disablePreferenceItem_network_dhcp", "Boolean", ""},
	{"Disable Digital Pointer Preferences", "disablePreferenceItem_fire_prefs_category", "Boolean", ""},
	{"Disable Disable Screen Saver / Screen Lock", "disablePreferenceItem_atakScreenLock", "Boolean", ""},
	{"Disable Disable SoftKey Illumination", "disablePreferenceItem_atakDisableSoftkeyIllumination", "Boolean", ""},
	{"Disable Display Bloodhound Text Widget", "disablePreferenceItem_rab_bloodhound_display_textwidget", "Boolean", ""},
	{"Disable Display Connection Widget", "disablePreferenceItem_displayServerConnectionWidget", "Boolean", ""},
	{"Disable Display Large Bloodhound Text Widget", "disablePreferenceItem_rab_bloodhound_large_textwidget", "Boolean", ""},
	{"Disable Display °M Unit in Doghouse", "disablePreferenceItem_doghouseShowNorthReference", "Boolean", ""},
	{"Disable Display Notification", "disablePreferenceItem_enableToast", "Boolean", ""},
	{"Disable Display Notifications for other users", "disablePreferenceItem_atakControlOtherUserNotification", "Boolean", ""},
	{"Disable Display Preferences", "disablePreferenceItem_generalDisplayPref", "Boolean", ""},
	{"Disable Display the Self Coordinate Information", "disablePreferenceItem_show_self_coordinate_overlay", "Boolean", ""},
	{"Disable DNS 1", "disablePreferenceItem_network_static_dns1", "Boolean", ""},
	{"Disable DNS 2", "disablePreferenceItem_network_static_dns2", "Boolean", ""},
	{"Disable Download attempts", "disablePreferenceItem_fileshareDownloadAttempts", "Boolean", ""},
	{"Disable DP/RedX FAH Width", "disablePreferenceItem_spiFahSize", "Boolean", ""},
	{"Disable DP Update Period", "disablePreferenceItem_spiUpdateDelay", "Boolean", ""},
	{"Disable Driving Checkpoint Navigation Bubble Radius", "disablePreferenceItem_waypointBubble.Driving", "Boolean", ""},
	{"Disable Driving Off Route Bubble Radius", "disablePreferenceItem_waypointOffRouteBubble.Driving", "Boolean", ""},
	{"Disable Dynamic Reporting Rate Maximum (Reliable)", "disablePreferenceItem_dynamicReportingRateMaxReliable", "Boolean", ""},
	{"Disable Dynamic Reporting Rate Maximum (Unreliable)", "disablePreferenceItem_dynamicReportingRateMaxUnreliable", "Boolean", ""},
	{"Disable Dynamic Reporting Rate Minimum (Reliable)", "disablePreferenceItem_dynamicReportingRateMinReliable", "Boolean", ""},
	{"Disable Dynamic Reporting Rate Minimum (Unreliable)", "disablePreferenceItem_dynamicReportingRateMinUnreliable", "Boolean", ""},
	{"Disable Dynamic Reporting Rate Stationary (Reliable)", "disablePreferenceItem_dynamicReportingRateStationaryReliable", "Boolean", ""},
	{"Disable Dynamic Reporting Rate Stationary (Unreliable)", "disablePreferenceItem_dynamicReportingRateStationaryUnreliable", "Boolean", ""},
	{"Disable Elevation Overlays Preferences", "disablePreferenceItem_dtedPreference", "Boolean", ""},
	{"Disable Elevation Profile Center on Seeker", "disablePreferenceItem_elevProfileCenterOnSeeker", "Boolean", ""},
	{"Disable Elevation Profile Interpolate Altitudes", "disablePreferenceItem_elevProfileInterpolateAlt", "Boolean", ""},
	{"Disable Enable Address Lookup (Geocoder)", "disablePreferenceItem_enableGeocoder", "Boolean", ""},
	{"Disable Enable Client Certificate Export", "disablePreferenceItem_certEnrollmentExport", "Boolean", ""},
	{"Disable Enable DEX Friendly Controls", "disablePreferenceItem_dexControls", "Boolean", ""},
	{"Disable Enable Globe Display Mode", "disablePreferenceItem_atakGlobeModeEnabled", "Boolean", ""},
	{"Disable Enable Image Overlay Map Interaction", "disablePreferenceItem_prefs_layer_grg_map_interaction", "Boolean", ""},
	{"Disable Enable Large Text Mode", "disablePreferenceItem_largeTextMode", "Boolean", ""},
	{"Disable Enable Large Tool Bar", "disablePreferenceItem_largeActionBar", "Boolean", ""},
	{"Disable Enable Map Scale Display", "disablePreferenceItem_map_scale_visible", "Boolean", ""},
	{"Disable Enable Map Scale Rounding", "disablePreferenceItem_map_scale_rounding", "Boolean", ""},
	{"Disable Enable Mesh Network Mode", "disablePreferenceItem_enableNonStreamingConnections", "Boolean", ""},
	{"Disable Enable the Faux Navigation Bar", "disablePreferenceItem_faux_nav_bar", "Boolean", ""},
	{"Disable Enable Volume Keys rotating map layers", "disablePreferenceItem_volumemapswitcher", "Boolean", ""},
	{"Disable Expanded Danger Close Search", "disablePreferenceItem_expandedDangerClose", "Boolean", ""},
	{"Disable Export Chat History", "disablePreferenceItem_exportHistory", "Boolean", ""},
	{"Disable Fade Notification Time", "disablePreferenceItem_fade_notification", "Boolean", ""},
	{"Disable FAH Distance (NM)", "disablePreferenceItem_fahDistance", "Boolean", ""},
	{"Disable File Transfer Connection Timeout", "disablePreferenceItem_filesharingConnectionTimeoutSecs", "Boolean", ""},
	{"Disable File Transfer Failure Timeout", "disablePreferenceItem_filesharingTransferTimeoutSecs", "Boolean", ""},
	{"Disable File Transfer Max size", "disablePreferenceItem_filesharingSizeThresholdNoGo", "Boolean", ""},
	{"Disable Fires Toolbar Preferences", "disablePreferenceItem_firesPreference", "Boolean", ""},
	{"Disable Flash Color", "disablePreferenceItem_bloodhound_flash_color_pref", "Boolean", ""},
	{"Disable Flash ETA Threshold", "disablePreferenceItem_bloodhound_flash_eta", "Boolean", ""},
	{"Disable Flash When Closing In", "disablePreferenceItem_rab_bloodhound_flash_colors", "Boolean", ""},
	{"Disable Flying Checkpoint Navigation Bubble Radius", "disablePreferenceItem_waypointBubble.Flying", "Boolean", ""},
	{"Disable Flying Off Route Bubble Radius", "disablePreferenceItem_waypointOffRouteBubble.Flying", "Boolean", ""},
	{"Disable Forced Application Brightness", "disablePreferenceItem_atakForcedBrightness", "Boolean", ""},
	{"Disable Force Reset Layer Cache", "disablePreferenceItem_mediaLayerCacheForceRescan", "Boolean", ""},
	{"Disable GPS Option", "disablePreferenceItem_mockingOption", "Boolean", ""},
	{"Disable GPS Preferences", "disablePreferenceItem_gpsSettings", "Boolean", ""},
	{"Disable GPS Preferences", "disablePreferenceItem_networkGpsCategory", "Boolean", ""},
	{"Disable GPX Import Checkpoints", "disablePreferenceItem_gpxImportCheckpointsForNamedRoutePoints", "Boolean", ""},
	{"Disable Grid Line Preferences", "disablePreferenceItem_gridLinesPreference", "Boolean", ""},
	{"Disable Disable my current position", "disablePreferenceItem_dispatchLocationHidden", "Boolean", ""},
	{"Disable Icon and Text Size", "disablePreferenceItem_relativeOverlaysScalingRadioList", "Boolean", ""},
	{"Disable Idle Stream", "disablePreferenceItem_video_dropdown_hidden_disconnect", "Boolean", ""},
	{"Disable Ignore Elevation Data", "disablePreferenceItem_kmlExportGroundClamp", "Boolean", ""},
	{"Disable Imagery Layer Outline Preferences", "disablePreferenceItem_layerOutlinesPreference", "Boolean", ""},
	{"Disable Imagery Tab Name", "disablePreferenceItem_imagery_tab_name", "Boolean", ""},
	{"Disable Import Style Default Preferences", "disablePreferenceItem_overlayStylePreference", "Boolean", ""},
	{"Disable Individual Alert Notifications", "disablePreferenceItem_individual_alert_notification", "Boolean", ""},
	{"Disable Inner ETA Color", "disablePreferenceItem_bloodhound_inner_color_pref", "Boolean", ""},
	{"Disable Internal Network Configuration", "disablePreferenceItem_network_config", "Boolean", ""},
	{"Disable IP address", "disablePreferenceItem_network_static_ip_address", "Boolean", ""},
	{"Disable KML Export Checkpoint Mode", "disablePreferenceItem_kmlExportCheckpointMode", "Boolean", ""},
	{"Disable KML Export Timestamps", "disablePreferenceItem_track_kml_export_timestamps", "Boolean", ""},
	{"Disable Laser Basket Distance (NM)", "disablePreferenceItem_laserBasketDistance", "Boolean", ""},
	{"Disable Legacy Settings View", "disablePreferenceItem_legacy_settings", "Boolean", ""},
	{"Disable Legacy Toolbar Mode", "disablePreferenceItem_legacyFiresToolbarMode", "Boolean", ""},
	{"Disable Legacy Wave Relay Redirect", "disablePreferenceItem_waveRelayRedirect", "Boolean", ""},
	{"Disable Load Preference Category", "disablePreferenceItem_loadPartialPrefs", "Boolean", ""},
	{"Disable Load Preferences", "disablePreferenceItem_loadPrefs", "Boolean", ""},
	{"Disable Logging Preferences", "disablePreferenceItem_settingsLogging", "Boolean", ""},
	{"Disable Log Tracks", "disablePreferenceItem_toggle_log_tracks", "Boolean", ""},
	{"Disable Manage Inputs", "disablePreferenceItem_manageInputsLink", "Boolean", ""},
	{"Disable Manage Outputs", "disablePreferenceItem_manageOutputsLink", "Boolean", ""},
	{"Disable Manage Persisted IDs", "disablePreferenceItem_tadiljPersistedIds", "Boolean", ""},
	{"Disable Manage Server Connections", "disablePreferenceItem_manageStreamingLink", "Boolean", ""},
	{"Disable Map Data Preferences", "disablePreferenceItem_wmsPreferences", "Boolean", ""},
	{"Disable Map Overlays Dimming/Brightening", "disablePreferenceItem_dim_map_with_brightness_key", "Boolean", ""},
	{"Disable Media Preferences", "disablePreferenceItem_mediaPreference", "Boolean", ""},
	{"Disable Metric Report Preferences", "disablePreferenceItem_metricsPreference", "Boolean", ""},
	{"Disable Middle ETA Color", "disablePreferenceItem_bloodhound_middle_color_pref", "Boolean", ""},
	{"Disable Middle/Inner ETA Threshold", "disablePreferenceItem_bloodhound_inner_eta", "Boolean", ""},
	{"Disable Mission Package Control Preferences", "disablePreferenceItem_missionpackagePreference", "Boolean", ""},
	{"Disable Monitor Server Connections", "disablePreferenceItem_monitorServerConnections", "Boolean", ""},
	{"Disable MulticastRejoin interval", "disablePreferenceItem_udpNoDataTimeout", "Boolean", ""},
	{"Disable Multicast Traffic Loopback", "disablePreferenceItem_network_multicast_loopback", "Boolean", ""},
	{"Disable Multicast TTL", "disablePreferenceItem_multicastTTL", "Boolean", ""},
	{"Disable My Callsign", "disablePreferenceItem_locationCallsign", "Boolean", ""},
	{"Disable My Callsign", "disablePreferenceItem_myIdentity", "Boolean", ""},
	{"Disable My Display Type", "disablePreferenceItem_locationUnitType", "Boolean", ""},
	{"Disable My Location Color / Size", "disablePreferenceItem_my_location_icon_color", "Boolean", ""},
	{"Disable My Preferences", "disablePreferenceItem_mySettings", "Boolean", ""},
	{"Disable My Role", "disablePreferenceItem_atakRoleType", "Boolean", ""},
	{"Disable My Team", "disablePreferenceItem_locationTeam", "Boolean", ""},
	{"Disable Navigational Voice Cues", "disablePreferenceItem_useRouteVoiceCues", "Boolean", ""},
	{"Disable Network Connection Preferences", "disablePreferenceItem_networkSettings", "Boolean", ""},
	{"Disable Network GPS", "disablePreferenceItem_gpsSettings", "Boolean", ""},
	{"Disable Network GPS", "disablePreferenceItem_networkCategory", "Boolean", ""},
	{"Disable Network GPS Option", "disablePreferenceItem_mockingOption", "Boolean", ""},
	{"Disable Network GPS Port", "disablePreferenceItem_listenPort", "Boolean", ""},
	{"Disable Network Preferences", "disablePreferenceItem_settingsPref", "Boolean", ""},
	{"Disable NGA Memorandum for Record (PFI)", "disablePreferenceItem_ngaCertification", "Boolean", ""},
	{"Disable Notification", "disablePreferenceItem_alert_notification", "Boolean", ""},
	{"Disable Number of DPs", "disablePreferenceItem_firesNumberOfSpis", "Boolean", ""},
	{"Disable Off-Screen Indicators Preferences", "disablePreferenceItem_atakOffScrIndiOptions", "Boolean", ""},
	{"Disable Outer ETA Color", "disablePreferenceItem_bloodhound_outer_color_pref", "Boolean", ""},
	{"Disable Outer/Middle ETA Threshold", "disablePreferenceItem_bloodhound_outer_eta", "Boolean", ""},
	{"Disable Overlay Manager Width/Height", "disablePreferenceItem_overlay_manager_width_height", "Boolean", ""},
	{"Disable Persistent Self Track", "disablePreferenceItem_track_infinite", "Boolean", ""},
	{"Disable Point-to-Point Link High Speed Capable", "disablePreferenceItem_ppp0_highspeed_capable", "Boolean", ""},
	{"Disable Prepare for Cloning / Clear Device unique information", "disablePreferenceItem_prepareForClone", "Boolean", ""},
	{"Disable Publish phone number", "disablePreferenceItem_saHasPhoneNumber", "Boolean", ""},
	{"Disable Publish Preferred Email", "disablePreferenceItem_saEmailAddress", "Boolean", ""},
	{"Disable Publish VoIP Number", "disablePreferenceItem_saSipAddressAssignment", "Boolean", ""},
	{"Disable Publish XMPP Username", "disablePreferenceItem_saXmppUsername", "Boolean", ""},
	{"Disable Redeploy WMS Sources", "disablePreferenceItem_redeploywms", "Boolean", ""},
	{"Disable Render bread crumb line to ground in 3-D", "disablePreferenceItem_track_line_to_surface", "Boolean", ""},
	{"Disable Render Speed", "disablePreferenceItem_frame_limit", "Boolean", ""},
	{"Disable Reporting Preferences", "disablePreferenceItem_publishCategory", "Boolean", ""},
	{"Disable Reporting Preferences", "disablePreferenceItem_reportingSettings", "Boolean", ""},
	{"Disable Reporting Strategy", "disablePreferenceItem_locationReportingStrategy", "Boolean", ""},
	{"Disable Report Location before obtaining location fix", "disablePreferenceItem_dispatchLocationCotExternalAtStart", "Boolean", ""},
	{"Disable Request Delay", "disablePreferenceItem_requestDelay", "Boolean", ""},
	{"Disable Reroute distance", "disablePreferenceItem_bloodhound_reroute_distance_pref", "Boolean", ""},
	{"Disable Reroute timer frequency", "disablePreferenceItem_bloodhound_reroute_timer_pref", "Boolean", ""},
	{"Disable Reset Hints", "disablePreferenceItem_resetHints", "Boolean", ""},
	{"Disable Reset Tool Bar Colors To Default", "disablePreferenceItem_default_actionbar_colors", "Boolean", ""},
	{"Disable Reverse Landscape Orientation", "disablePreferenceItem_atakControlReverseOrientation", "Boolean", ""},
	{"Disable Reverse the buttons on the Faux Navigation Bar", "disablePreferenceItem_faux_nav_bar_reverse", "Boolean", ""},
	{"Disable Route Preferences", "disablePreferenceItem_routePreference", "Boolean", ""},
	{"Disable Rover Control Preferences", "disablePreferenceItem_isrvNetworkPreference", "Boolean", ""},
	{"Disable Save Preferences", "disablePreferenceItem_savePrefs", "Boolean", ""},
	{"Disable Secure Server API port", "disablePreferenceItem_apiSecureServerPort", "Boolean", ""},
	{"Disable Send Location Over Network", "disablePreferenceItem_dispatchLocationCotExternal", "Boolean", ""},
	{"Disable Server port", "disablePreferenceItem_filesharingWebServerPort", "Boolean", ""},
	{"Disable Server track time gap (minutes)", "disablePreferenceItem_bread_track_timegap_threshold", "Boolean", ""},
	{"Disable Set Distance Threshold (KM)", "disablePreferenceItem_offscreen_indicator_dist_threshold", "Boolean", ""},
	{"Disable Set Max Number of Bread Crumbs", "disablePreferenceItem_max_num_bread_tracks", "Boolean", ""},
	{"Disable Set Timeout Threshold (seconds) or zero to disable", "disablePreferenceItem_offscreen_indicator_timeout_threshold", "Boolean", ""},
	{"Disable Shorten Long Marker Labels", "disablePreferenceItem_atakControlShortenLabels", "Boolean", ""},
	{"Disable Show All Preferences", "disablePreferenceItem_atakControlOptions", "Boolean", ""},
	{"Disable Show Attachment Billboards", "disablePreferenceItem_route_billboard_enabled", "Boolean", ""},
	{"Disable Show by Default", "disablePreferenceItem_prefs_dted_visible", "Boolean", ""},
	{"Disable Show Marker Labels", "disablePreferenceItem_atakControlShowLabels", "Boolean", ""},
	{"Disable Subnet mask", "disablePreferenceItem_network_static_subnet_mask", "Boolean", ""},
	{"Disable Support", "disablePreferenceItem_documentation", "Boolean", ""},
	{"Disable Swimming Checkpoint Navigation Bubble Radius", "disablePreferenceItem_waypointBubble.Swimming", "Boolean", ""},
	{"Disable Swimming Off Route Bubble Radius", "disablePreferenceItem_waypointOffRouteBubble.Swimming", "Boolean", ""},
	{"Disable TADIL-J Preferences", "disablePreferenceItem_tadiljSettings", "Boolean", ""},
	{"Disable TAK Device Configuration", "disablePreferenceItem_resetDeviceConfig", "Boolean", ""},
	{"Disable TAK Package Mgmt", "disablePreferenceItem_appsPref", "Boolean", ""},
	{"Disable TAK Package Mgmt", "disablePreferenceItem_myPlugins", "Boolean", ""},
	{"Disable TAK Servers", "disablePreferenceItem_myServers", "Boolean", ""},
	{"Disable TAK Support Information", "disablePreferenceItem_atakSupport", "Boolean", ""},
	{"Disable TCP Connection Timeout", "disablePreferenceItem_tcpConnectTimeout", "Boolean", ""},
	{"Disable Team Color", "disablePreferenceItem_team_color_gps_icon", "Boolean", ""},
	{"Disable Test Address Provider", "disablePreferenceItem_geocodeTestConnection", "Boolean", ""},
	{"Disable Toggle Auto Zoom", "disablePreferenceItem_rab_bloodhound_zoom", "Boolean", ""},
	{"Disable Tool Bar Background Color", "disablePreferenceItem_selected_actionbar_background_color", "Boolean", ""},
	{"Disable Tool Bar Customization", "disablePreferenceItem_my_actionbar_settings", "Boolean", ""},
	{"Disable Tool Bar Icon Color", "disablePreferenceItem_custom_actionbar_icon_color", "Boolean", ""},
	{"Disable Tool Preferences", "disablePreferenceItem_toolsPref", "Boolean", ""},
	{"Disable Track History Preferences", "disablePreferenceItem_atakTrackOptions", "Boolean", ""},
	{"Disable Track Prefix", "disablePreferenceItem_track_prefix", "Boolean", ""},
	{"Disable Traditional Navigation Mode", "disablePreferenceItem_route_track_up_locked_on", "Boolean", ""},
	{"Disable Unit Display Format Preferences", "disablePreferenceItem_unitPreferences", "Boolean", ""},
	{"Disable Unsecure Server API port", "disablePreferenceItem_apiUnsecureServerPort", "Boolean", ""},
	{"Disable Use Android Geocoder", "disablePreferenceItem_builtInGeocoder", "Boolean", ""},
	{"Disable Use GPS Time", "disablePreferenceItem_useGPSTime", "Boolean", ""},
	{"Disable Use Wave Relay Callsign", "disablePreferenceItem_locationUseWRCallsign", "Boolean", ""},
	{"Disable Vibrate phone", "disablePreferenceItem_vibratePhone", "Boolean", ""},
	{"Disable Vibrate When Arriving at Checkpoint", "disablePreferenceItem_route_vibrate_at_checkpoint", "Boolean", ""},
	{"Disable Vibration alert", "disablePreferenceItem_alert_vibration", "Boolean", ""},
	{"Disable Video Preferences", "disablePreferenceItem_videoPreference", "Boolean", ""},
	{"Disable VoIP Number", "disablePreferenceItem_saSipAddress", "Boolean", ""},
	{"Disable Walking Checkpoint Navigation Bubble Radius", "disablePreferenceItem_waypointBubble.Walking", "Boolean", ""},
	{"Disable Walking Off Route Bubble Radius", "disablePreferenceItem_waypointOffRouteBubble.Walking", "Boolean", ""},
	{"Disable Watercraft Checkpoint Navigation Bubble Radius", "disablePreferenceItem_waypointBubble.Watercraft", "Boolean", ""},
	{"Disable Watercraft Off Route Bubble Radius", "disablePreferenceItem_waypointOffRouteBubble.Watercraft", "Boolean", ""},
	{"Disable WMS Connect Timeout", "disablePreferenceItem_wmsconnecttimeout", "Boolean", ""},
	{"Disable Disable EUD Link", "disablePreferenceItem_eud_api_disable_option", "Boolean", ""},
}

func (p *PrefKey) Val(val string) string {
	if p == nil {
		return ""
	}

	return fmt.Sprintf("<entry key=\"%s\" class=\"class java.lang.%s\">%s</entry>", p.Key, p.Cls, val)
}

func GetEntry(key, val string) string {
	for _, p := range prefKeys {
		if p.Key == key {
			return p.Val(val)
		}
	}

	return ""
}
